In [1]:
# Fetch the data from different sources

# ICOS-Carbon-data- portal: https://github.com/ICOS-Carbon-Portal/data?tab=readme-ov-file#downloading-originals-programmatically

# Create an ICOS Carbon portal account: https://cpauth.icos-cp.eu/login/

In [2]:
import json
import os
import zipfile

import polars as pl
from icoscp_core.icos import bootstrap

In [3]:
token_file_path = "../tokens/cpauthToken_auth_conf.json"

In [ ]:
def get_icoscp_credentials(token_file_path):
    """Load the authentication token from the provided JSON file."""
    with open(token_file_path, "r") as f:
        credentials = json.load(f)
    return credentials


credentials = get_icoscp_credentials(token_file_path)

meta, data = bootstrap.fromCredentials(credentials["username"], credentials["password"])

In [5]:
# from icoscp_core.icos import meta

# fetches the list of known data types, including metadata associated with them
all_datatypes = meta.list_datatypes()

# data types with structured data access
previewable_datatypes = [dt for dt in all_datatypes if dt.has_data_access]

datatypes = [{"Description": dt.label, "uri": dt.uri} for dt in previewable_datatypes]

df = pl.DataFrame(datatypes)

df.write_csv("../data/intermediate/previewable_datatypes.csv")

df.head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ Description                     ┆ uri                             │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ AirCore vertical profile level… ┆ http://meta.icos-cp.eu/resourc… │
│ Atmospheric CH4 product         ┆ http://meta.icos-cp.eu/resourc… │
│ Atmospheric CO product          ┆ http://meta.icos-cp.eu/resourc… │
│ Atmospheric CO2 product         ┆ http://meta.icos-cp.eu/resourc… │
│ Atmospheric GHG data product    ┆ http://meta.icos-cp.eu/resourc… │
└─────────────────────────────────┴─────────────────────────────────┘

In [ ]:
# from icoscp_core.icos import meta

# Ecosystem final quality (L2) product in ETC-Archive format - release 2025-1
collection_uri = "https://meta.icos-cp.eu/collections/1-HA2r4l5QUjAgQr5CCEfJe3"

""" 
The Level 2 Ecosystem collection consists of many zipped parts for 
individual stations and components. Examples (as shown on the collection page) 
include:
*_FLUXES_L2.zip — Flux measurements (GPP, NEE, latent/sensible heat)
*_METEO_L2.zip — Meteorological variables (radiation, temperature, humidity, 
    wind, etc.)
*_AUXDATA_L2.zip — Ancillary/biometric measurements

"""

collection_meta = meta.get_collection_meta(collection_uri)

members = collection_meta.members

In [7]:
collection_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"
collection_meta = meta.get_station_meta(collection_uri)
print(dir(collection_meta))

['__annotate_func__', '__annotations__', '__annotations_cache__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__replace__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', 'countryCode', 'coverage', 'funding', 'id', 'location', 'org', 'pictures', 'responsibleOrganization', 'specificInfo', 'staff']

In [42]:
# Extract the uri for meteorological data

meteorological_urls = []
for mem in members:
    if hasattr(mem, "name") and hasattr(mem, "res"):
        name = mem.name
        if isinstance(name, str) and "METEO" in name:
            meteorological_urls.append(mem.res)
            # print(mem.res, name)

# Extract uri's for fluxes
flux_urls = []
for mem in members:
    if hasattr(mem, "name") and hasattr(mem, "res"):
        name = mem.name
        if isinstance(name, str) and "FLUXES_L2" in name:
            flux_urls.append(mem.res)
            # print(mem.res, name)

# Extract uri's for ancillary measurememnts
aux_urls = []
for mem in members:
    if hasattr(mem, "name") and hasattr(mem, "res"):
        name = mem.name
        if isinstance(name, str) and "AUXDATA" in name:
            aux_urls.append(mem.res)
            print(mem.res, name)

https://meta.icos-cp.eu/objects/MM03ZcoXByiQxNVDdaLQpM5z ICOSETC_BE-Bra_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/GTzxWow0u-RMUyykrPBvz5S1 ICOSETC_BE-Dor_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/Jtx_PJ1BGsl4o_o5oxtzyDd3 ICOSETC_BE-Lon_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/OxCaJl5bOkt-dWtoTzpYSPTd ICOSETC_BE-Maa_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/nsk8uCwLjbfh84hFlqZFw6AK ICOSETC_BE-Vie_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/DYbIBsXgz_3i17ZQctm80T2a ICOSETC_CH-Dav_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/R3l0tIWfq2jdXzojN4po2PkX ICOSETC_CZ-BK1_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/DSanpeYslisBVe8CF0HfY6bK ICOSETC_CZ-Lnz_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/B2JP5gN7RMNiyO7dKX5Yiaag ICOSETC_DE-Geb_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/04LgrLThcOIc6oI1bBCC9x1V ICOSETC_DE-HoH_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/wOQuQd4XKFiBvN4PT9WpHZYT ICOSETC_DE-RuS_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/LCGhDA_nG16TbohHL37n5H6k ICOSETC_DE-Tha_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/_LegDvMJYfp8vdWaAaqbuXyy ICOSETC_DK-Sor_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/byegYHnpaxypESQlRnvIfbhy ICOSETC_FI-Hyy_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/3pXBEYoqtyxYfGhi4u5XDDng ICOSETC_FI-Sii_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/mmxvHR6vJO4EZd98q51f4-d0 ICOSETC_FI-Sod_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/T_enf79kwiDW8sxgji2mkfJ9 ICOSETC_FR-Bil_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/0K2uT9MfYPXETvHMBejba2gS ICOSETC_FR-FBn_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/IuXvjwulCRz5Bm8SyFsZ4M71 ICOSETC_FR-Fon_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/WNWfnsIQoB11q-9CTin_M9U2 ICOSETC_FR-Gri_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/cDGZMyMjvFSvHIc2RgV8oVE_ ICOSETC_FR-Hes_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/Wd4WqW3xPmYNzjphheAvI4zg ICOSETC_FR-Lqu_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/oBPL4Pz91kxAxB1LNZagIt1K ICOSETC_FR-Lus_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/JJYgMqFVviapfoz0yP_ouPhy ICOSETC_FR-Pue_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/Xf4URAcXPPwz7cmJKyZIts5B ICOSETC_GL-ZaF_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/QgWYGLdx1bgL5_knKkDIXSg- ICOSETC_IT-BCi_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/iWJenD1OArpl_fVXCBFPAsGG ICOSETC_IT-Cp2_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/VE2YLP4JvPbfKhpK2ewYdQoY ICOSETC_IT-MBo_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/4Jg5S7ehP7YnGfiP745k0-39 ICOSETC_IT-Ren_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/O4BLQjMBjWu4ltQHSTsYH-vB ICOSETC_IT-SR2_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/VsWMN7T6uMWEpDt_J7F9bCcT ICOSETC_NL-Loo_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/c_uR_E4wfLbh6NwQt3VP9-o1 ICOSETC_NO-Hur_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/oRnaJZacbKW46Ys8fZW_l_As ICOSETC_SE-Deg_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/CMb9gSUs7c2fHF6_FTzXFiqF ICOSETC_SE-Htm_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/gNf_IhDgS8smAQUvWh81RpC9 ICOSETC_SE-Nor_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/zwH1N7YZoY7oTXdqqAzuBaFT ICOSETC_SE-Sto_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/bcXdx4-dHxAERYR3bUdphFZ7 ICOSETC_SE-Svb_AUXDATA_L2.zip
https://meta.icos-cp.eu/objects/TgEd-5XOpvUsUZxe8gGtQAy5 ICOSETC_UK-AMo_AUXDATA_L2.zip

In [41]:
n20_urls = []
for mem in members:
    if hasattr(mem, "name") and hasattr(mem, "res"):
        name = mem.name
        if isinstance(name, str) and "N2O" in name:
            n20_urls.append(mem.res)
            print(mem.res, name)

In [10]:
from icoscp_core.icos import ATMO_STATION, meta

# fetch lists of stations, with basic metadata
icos_stations = meta.list_stations()
atmo_stations = meta.list_stations(ATMO_STATION)
all_known_stations = meta.list_stations(False)

# get detailed metadata for a station
htm_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"
htm_station_meta = meta.get_station_meta(htm_uri)

htm_station_meta

Station(org=Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', label='HTM', comments=[]), name='Hyltemossa', email=None, website=None, webpageDetails=None), id='HTM', location=Position(lat=56.0976, lon=13.4189, alt=115.0, label='HTM', uri=None), coverage=None, responsibleOrganization=Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CEC', label='CEC', comments=[]), name='Centre for Environmental and Climate Science, Lund University', email=None, website='https://www.cec.lu.se', webpageDetails=None), pictures=['https://meta.icos-cp.eu/files/655_ISiY9jPRX2HHmCEW1_ux/Hyltemossa%202.JPG'], specificInfo=AtcStationSpecifics(wigosId='0-20008-0-HTM', theme=DataTheme(self=UriResource(uri='http://meta.icos-cp.eu/resources/themes/atmosphere', label='Atmospheric data', comments=[]), icon='https://static.icos-cp.eu/images/themes/atm.svg', markerIcon='https://static.icos-cp.eu/share/stations/icons/as.png'), stationClass='1', labelingDate='2018-05-31', discontinued=False, timeZoneOffset=1, documentation=[PlainStaticObject(res='https://meta.icos-cp.eu/objects/FtAw9aAzcJWX2CdQ8rBwecOg', hash='FtAw9aAzcJWX2CdQ8rBwecOgYL37LfIj-Z-zBkOfOyQ', name='STILT station characterization for Hyltemossa at 150m')]), countryCode='SE', funding=None, staff=[Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Tobias_Biermann', label=None, comments=[]), firstName='Tobias', lastName='Biermann', email='tobias.biermann@mgeo.lu.se', orcid='0000-0001-8538-1495'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/PI', label='Principal Investigator', comments=[]), start='2017-04-17T00:00:00Z', end=None, weight=20, extra=None)), Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Michal_Heliasz', label=None, comments=[]), firstName='Michal', lastName='Heliasz', email='michal.heliasz@mgeo.lu.se', orcid='0000-0003-2635-9604'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/PI', label='Principal Investigator', comments=[]), start='2017-04-17T00:00:00Z', end=None, weight=70, extra=None)), Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Meelis_M%C3%B6lder', label=None, comments=[]), firstName='Meelis', lastName='Molder', email='meelis.molder@mgeo.lu.se', orcid='0000-0001-6767-3195'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/Engineer', label='Engineer', comments=[]), start='2017-04-17T00:00:00Z', end='2024-01-01T00:00:00Z', weight=None, extra=None))])

In [11]:
# Creating a table for ICOS stations
icos_stations = meta.list_stations()
station_data = []
schema = ["Id", "Label", "Name", "Country code", "Lat", "Lon"]

for station in icos_stations:
    station_data.append(
        {
            "Id": station.type_uri,
            "Label": station.label,
            "Name": station.name,
            "Country code": station.country_code,
            "Lat": station.lat,
            "Lon": station.lon,
        }
    )

station_data = pl.DataFrame(
    station_data,
    schema=schema,
)

station_data

shape: (512, 6)
┌───────────────────┬───────────────────┬───────────────────┬──────────────┬───────────┬───────────┐
│ Id                ┆ Label             ┆ Name              ┆ Country code ┆ Lat       ┆ Lon       │
│ ---               ┆ ---               ┆ ---               ┆ ---          ┆ ---       ┆ ---       │
│ str               ┆ str               ┆ str               ┆ str          ┆ f64       ┆ f64       │
╞═══════════════════╪═══════════════════╪═══════════════════╪══════════════╪═══════════╪═══════════╡
│ http://meta.icos- ┆ El Arenosillo     ┆ El Arenosillo     ┆ ES           ┆ 37.104    ┆ -6.734    │
│ cp.eu/ontolog…    ┆ (ARN)             ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Innsbruck         ┆ Innsbruck         ┆ AT           ┆ 47.264095 ┆ 11.385816 │
│ cp.eu/ontolog…    ┆ (AT-Inn)          ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Mieming (AT-Mmg)  ┆ Mieming           ┆ AT           ┆ 47.316563 ┆ 10.970089 │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Neustift (AT-Neu) ┆ Neustift          ┆ AT           ┆ 47.116318 ┆ 11.320229 │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Puergschachen     ┆ Puergschachen     ┆ AT           ┆ 47.58145  ┆ 14.347197 │
│ cp.eu/ontolog…    ┆ Moor (AT-PsM)     ┆ Moor              ┆              ┆           ┆           │
│ …                 ┆ …                 ┆ …                 ┆ …            ┆ …         ┆ …         │
│ http://meta.icos- ┆ Umhlabuyalingana  ┆ Umhlabuyalingana  ┆ ZA           ┆ -27.3952  ┆ 32.5889   │
│ cp.eu/ontolog…    ┆ (ZA-Uby)          ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Zeppelin (ZEP)    ┆ Zeppelin          ┆ NO           ┆ 78.9072   ┆ 11.8867   │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Zotino (ZOT)      ┆ Zotino            ┆ RU           ┆ 64.48     ┆ 89.21     │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Zugspitze (ZSF)   ┆ Zugspitze         ┆ DE           ┆ 47.4165   ┆ 10.9796   │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
│ http://meta.icos- ┆ Zugspitze (ZUG)   ┆ Zugspitze         ┆ DE           ┆ 47.4211   ┆ 10.9859   │
│ cp.eu/ontolog…    ┆                   ┆                   ┆              ┆           ┆           │
└───────────────────┴───────────────────┴───────────────────┴──────────────┴───────────┴───────────┘

In [12]:
icos_stations

[StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_ARN', label='El Arenosillo (ARN)', comments=[], id='ARN', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='El Arenosillo', country_code='ES', lat=37.104, lon=-6.734, elevation=42.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-Inn_2', label='Innsbruck (AT-Inn)', comments=[], id='AT-Inn', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Innsbruck', country_code='AT', lat=47.264095, lon=11.385816, elevation=574.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-Mmg', label='Mieming (AT-Mmg)', comments=[], id='AT-Mmg', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Mieming', country_code='AT', lat=47.316563, lon=10.970089, elevation=960.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-Neu', label='Neustift (AT-Neu)', comments=[], id='AT-Neu', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Neustift', country_code='AT', lat=47.116318, lon=11.320229, elevation=970.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-PsM', label='Puergschachen Moor (AT-PsM)', comments=[], id='AT-PsM', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Puergschachen Moor', country_code='AT', lat=47.58145, lon=14.347197, elevation=631.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-Rtz', label='Rotholz (AT-Rtz)', comments=[], id='AT-Rtz', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Rotholz', country_code='AT', lat=47.394722, lon=11.804722, elevation=523.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-VnA', label='Vienna Arsenal (AT-VnA)', comments=[], id='AT-VnA', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Vienna Arsenal', country_code='AT', lat=48.18184, lon=16.39085, elevation=None, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_AT-Zoe', label='Zoebelboden (AT-Zoe)', comments=[], id='AT-Zoe', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Zoebelboden', country_code='AT', lat=47.842247, lon=14.444137, elevation=956.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Bra', label='Brasschaat (BE-Bra)', comments=[], id='BE-Bra', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Brasschaat', country_code='BE', lat=51.30761, lon=4.51984, elevation=16.0, geo_json='{"features":[{"geometry":{"coordinates":[[[4.515144,51.306127],[4.515459,51.305305],[4.517269,51.305751],[4.517259,51.305748],[4.519518,51.306159],[4.522698,51.306834],[4.52116,51.309808],[4.515144,51.306127]]],"type":"Polygon"},"properties":{"label":"TA"},"type":"Feature"},{"geometry":{"coordinates":[4.519527,51.307566],"type":"Point"},"properties":{"radius":25.19},"type":"Feature"},{"geometry":{"coordinates":[4.519445,51.308405],"type":"Point"},"properties":{"radius":25.19},"type":"Feature"},{"geometry":{"coordinates":[4.520389,51.307602],"type":"Point"},"properties":{"radius":25.19},"type":"Feature"},{"geometry":{"coordinates":[4.520098,51.30701],"type":"Point"},"properties":{"radius":25.19},"type":"Feature"}],"type":"FeatureCollection"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Dor', label='Dorinne (BE-Dor)', comments=[], id='BE-Dor', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Dorinne', country_code='BE', lat=50.311874, lon=4.968113, elevation=253.0, geo_json='{"coordinates":[[[4.969615,50.312834],[4.969426,50.312968],[4.969299,50.313058],[4.969151,50.312989],[4.968987,50.31291],[4.968915,50.312978],[4.968712,50.312912],[4.968401,50.312818],[4.968216,50.312774],[4.967751,50.312667],[4.967695,50.312668],[4.967606,50.312653],[4.967504,50.312658],[4.967422,50.312641],[4.967368,50.312613],[4.9673,50.312594],[4.967198,50.312618],[4.967097,50.312607],[4.967026,50.312522],[4.966965,50.312446],[4.966863,50.312332],[4.966911,50.312269],[4.966957,50.312215],[4.966796,50.31216],[4.966698,50.312143],[4.966641,50.312075],[4.96654,50.312001],[4.96645,50.311938],[4.966212,50.311846],[4.966267,50.311771],[4.966298,50.311697],[4.966325,50.311621],[4.966387,50.311384],[4.966467,50.311023],[4.966596,50.310563],[4.967095,50.310784],[4.967236,50.310839],[4.967362,50.310883],[4.967977,50.311047],[4.96878,50.311267],[4.969096,50.311567],[4.969461,50.311908],[4.969413,50.311981],[4.969414,50.312069],[4.969485,50.31212],[4.969564,50.312128],[4.96965,50.312086],[4.969698,50.312029],[4.969688,50.311977],[4.969793,50.312012],[4.969735,50.312211],[4.969671,50.312443],[4.969615,50.312834]]],"type":"Polygon"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/OS_1199', label='Thornton Buoy (BE-FOS-Thornton Buoy)', comments=[], id='BE-FOS-Thornton Buoy', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/OS', name='Thornton Buoy', country_code='BE', lat=51.57989, lon=2.993217, elevation=None, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Jal', label='La Robinette (Jalhay) (BE-Jal)', comments=[], id='BE-Jal', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='La Robinette (Jalhay)', country_code='BE', lat=50.56389, lon=6.0733333, elevation=486.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Lcr', label='Lochristi (BE-Lcr)', comments=[], id='BE-Lcr', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Lochristi', country_code='BE', lat=51.11218, lon=3.85043, elevation=6.25, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Lon', label='Lonzee (BE-Lon)', comments=[], id='BE-Lon', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Lonzee', country_code='BE', lat=50.55162, lon=4.746234, elevation=170.0, geo_json='{"features":[{"geometry":{"coordinates":[[[4.741999,50.552318],[4.744611,50.549445],[4.749457,50.552122],[4.747337,50.553296],[4.74729,50.553315],[4.747224,50.553334],[4.747136,50.553348],[4.747059,50.553353],[4.746981,50.553351],[4.746576,50.553278],[4.745343,50.553017],[4.741999,50.552318]]],"type":"Polygon"},"properties":{"label":"TA"},"type":"Feature"},{"geometry":{"coordinates":[4.745862,50.551442],"type":"Point"},"properties":{"radius":5.58},"type":"Feature"},{"geometry":{"coordinates":[4.746202,50.551338],"type":"Point"},"properties":{"radius":5.58},"type":"Feature"}],"type":"FeatureCollection"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Maa', label='Maasmechelen (BE-Maa)', comments=[], id='BE-Maa', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Maasmechelen', country_code='BE', lat=50.97987, lon=5.631851, elevation=85.0, geo_json='{"features":[{"geometry":{"coordinates":[[[5.630596,50.979229],[5.63071,50.979161],[5.631113,50.979056],[5.6316,50.979096],[5.631811,50.97927],[5.631969,50.979455],[5.632642,50.979496],[5.632775,50.979554],[5.632947,50.979818],[5.632632,50.979954],[5.632593,50.980078],[5.632667,50.980236],[5.632672,50.980295],[5.632613,50.980322],[5.6307,50.980456],[5.630596,50.979229]]],"type":"Polygon"},"properties":{"label":"TA"},"type":"Feature"},{"geometry":{"coordinates":[5.630836,50.980082],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632313,50.980037],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.63101,50.979569],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.63083,50.980109],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631611,50.979809],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.63156,50.979851],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630977,50.979553],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631044,50.979584],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631108,50.979618],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631717,50.979722],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632327,50.980062],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631587,50.979831],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631143,50.979633],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632396,50.980217],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.63084,50.979918],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630837,50.979945],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631283,50.979691],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630827,50.980136],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631249,50.979674],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631534,50.979872],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632344,50.980086],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632387,50.980192],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631215,50.979659],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632301,50.98001],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.63237,50.980139],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630837,50.979972],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631483,50.979914],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630831,50.980162],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632356,50.980113],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632378,50.980166],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631508,50.979894],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.632406,50.98024],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631662,50.979766],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631076,50.979602],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630838,50.980027],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631181,50.979645],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631637,50.979787],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.631689,50.979745],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630837,50.98],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"},{"geometry":{"coordinates":[5.630835,50.980054],"type":"Point"},"properties":{"radius":0.42},"type":"Feature"}],"type":"FeatureCollection"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/OS_11BE', label='Belgica (BE-SOOP-Belgica)', comments=[], id='BE-SOOP-Belgica', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/OS', name='Belgica', country_code='BE', lat=None, lon=None, elevation=None, geo_json='{"coordinates":[[[3.195075,51.352665],[4.987649,53.548034],[1.937363,52.635883],[1.328389,51.745238],[0.800445,51.531345],[1.52255,51.425346],[1.419561,50.986182],[-3.70392,50.103603],[-5.960633,49.887639],[-8.203092,51.737461],[-8.807063,51.478761],[-9.463657,51.388688],[-10.275141,51.569215],[-10.547177,51.856524],[-10.035075,52.101085],[-12.947524,51.581197],[-12.875805,42.867814],[-9.485461,36.322672],[-6.242154,36.101191],[-9.240806,37.058412],[-9.772257,39.58497],[-9.260096,43.306811],[-7.747654,43.870554],[-1.752647,43.64556],[-1.517553,45.791491],[-4.964788,48.094431],[-5.142982,48.65371],[-1.695974,49.796877],[-0.693411,49.67271],[1.242599,50.158143],[1.741501,51.093598],[3.195075,51.352665]]],"type":"Polygon"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/OS_11SS', label='Simon Stevin (BE-SOOP-Simon Stevin)', comments=[], id='BE-SOOP-Simon Stevin', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/OS', name='Simon Stevin', country_code='BE', lat=None, lon=None, elevation=None, geo_json='{"coordinates":[[[3.490085,51.4195],[3.859583,51.341723],[3.98443,51.407737],[4.129314,51.38915],[4.406813,51.249782],[4.143052,51.39734],[3.980889,51.450037],[3.733259,51.412944],[3.198701,51.500922],[3.000542,51.602947],[2.800769,51.647011],[2.299241,51.499901],[2.565305,51.110266],[2.896795,51.226358],[3.490085,51.4195]]],"type":"Polygon"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Vie', label='Vielsalm (BE-Vie)', comments=[], id='BE-Vie', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Vielsalm', country_code='BE', lat=50.304962, lon=5.998099, elevation=490.0, geo_json='{"features":[{"geometry":{"coordinates":[5.997619,50.304971],"type":"Point"},"properties":{"radius":25.18},"type":"Feature"},{"geometry":{"coordinates":[5.998718,50.305067],"type":"Point"},"properties":{"radius":25.18},"type":"Feature"},{"geometry":{"coordinates":[5.99871,50.306918],"type":"Point"},"properties":{"radius":25.18},"type":"Feature"},{"geometry":{"coordinates":[[[5.992434,50.306327],[5.992461,50.30596],[5.992089,50.30558],[5.992017,50.305183],[5.991937,50.304836],[5.991997,50.304599],[5.992742,50.304259],[5.992088,50.303846],[5.992841,50.303736],[5.992829,50.303388],[5.992315,50.303109],[5.99285,50.302306],[5.993909,50.301509],[5.994044,50.301469],[5.994282,50.301615],[5.99656,50.301844],[5.997553,50.30193],[5.998957,50.302134],[5.99903,50.302126],[5.999188,50.302102],[5.999477,50.302048],[6.001029,50.302209],[6.00096,50.30237],[6.000906,50.302523],[6.00083,50.302778],[6.000453,50.304157],[6.001269,50.30452],[6.002463,50.303926],[6.003821,50.305224],[6.005068,50.305263],[6.004992,50.305784],[6.004707,50.306241],[6.00482,50.306724],[6.004644,50.307249],[6.004238,50.307562],[6.004193,50.307722],[6.004103,50.307878],[6.003333,50.30805],[6.003273,50.308573],[6.001917,50.308655],[6.00084,50.308931],[6.00024,50.308977],[5.999672,50.308823],[5.99951,50.308639],[5.998788,50.308537],[5.998374,50.308332],[5.997734,50.308341],[5.997417,50.308159],[5.997547,50.307995],[5.997308,50.307812],[5.996665,50.307747],[5.995774,50.307679],[5.9956,50.307811],[5.994793,50.307475],[5.992962,50.306705],[5.992434,50.306327]]],"type":"Polygon"},"properties":{"label":"TA"},"type":"Feature"}],"type":"FeatureCollection"}'),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Wm1', label='Westmalle1 (BE-Wm1)', comments=[], id='BE-Wm1', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Westmalle1', country_code='BE', lat=51.296432, lon=4.6572485, elevation=None, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BE-Wm2', label='Westmalle2 (BE-Wm2)', comments=[], id='BE-Wm2', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Westmalle2', country_code='BE', lat=51.29747, lon=4.6624384, elevation=None, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_BIK', label='Bialystok (BIK)', comments=[], id='BIK', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Bialystok', country_code='PL', lat=53.2294, lon=23.0128, elevation=183.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_BIR', label='Birkenes (BIR)', comments=[], id='BIR', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Birkenes', country_code='NO', lat=58.3886, lon=8.2519, elevation=219.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_BIS', label='Biscarrosse (BIS)', comments=[], id='BIS', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Biscarrosse', country_code='FR', lat=44.3781, lon=-1.2311, elevation=73.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BJ-Bfg', label='Bellefoungou (BJ-Bfg)', comments=[], id='BJ-Bfg', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Bellefoungou', country_code='BJ', lat=9.791, lon=1.718, elevation=445.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BJ-Db1', label='DANGBO (BJ-Db1)', comments=[], id='BJ-Db1', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='DANGBO', country_code='BJ', lat=6.607338, lon=2.543043, elevation=54.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BJ-Nhu', label='Nalohou (BJ-Nhu)', comments=[], id='BJ-Nhu', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Nalohou', country_code='BJ', lat=9.74, lon=1.6, elevation=449.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_BRM', label='Beromunster (BRM)', comments=[], id='BRM', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Beromunster', country_code='CH', lat=47.1896, lon=8.1755, elevation=797.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_BSD', label='Bilsdale (BSD)', comments=[], id='BSD', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Bilsdale', country_code='GB', lat=54.3586, lon=-1.1504, elevation=382.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BW-Gum', label='Guma (BW-Gum)', comments=[], id='BW-Gum', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Guma', country_code='BW', lat=-18.964722, lon=22.37111, elevation=983.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_BW-Nxr', label='Nxaraga (BW-Nxr)', comments=[], id='BW-Nxr', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Nxaraga', country_code='BW', lat=-19.548056, lon=23.179167, elevation=952.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/AS_CBW', label='Cabauw (CBW)', comments=[], id='CBW', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/AS', name='Cabauw', country_code='NL', lat=51.9703, lon=4.9264, elevation=0.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_CD-Ygb', label='Yangambi (CD-Ygb)', comments=[], id='CD-Ygb', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Yangambi', country_code='CD', lat=0.814444, lon=24.502472, elevation=466.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_CH-Aws', label='Alp Weissenstein (CH-Aws)', comments=[], id='CH-Aws', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Alp Weissenstein', country_code='CH', lat=46.58311, lon=9.790639, elevation=1978.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_CH-BaA', label='Basel Aeschenplatz (CH-BaA)', comments=[], id='CH-BaA', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Basel Aeschenplatz', country_code='CH', lat=47.55123, lon=7.5956, elevation=270.0, geo_json=None),
 StationLite(uri='http://meta.icos-cp.eu/resources/stations/ES_CH-BaK', label='Basel Klingelbergstrasse (CH-BaK)', comments=[], id='CH-BaK', type_uri='http://meta.icos-cp.eu/ontologies/cpmeta/ES', name='Basel Klingelbergstrasse', country_code='CH', lat=47.56173, lon=7.58049, elevation=273.0, geo_json=None),

In [13]:
from icoscp_core.metaclient import SamplingHeightFilter, SizeFilter, TimeFilter

# list data objects with basic metadata
# a contrived, complicated example to demonstrate the possibilities
# all the arguments are optional
# see the Python help for the method for more details
filtered_atc_co2 = meta.list_data_objects(
    datatype=[
        "http://meta.icos-cp.eu/resources/cpmeta/atcCo2L2DataObject",
        "http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject",
    ],
    station="http://meta.icos-cp.eu/resources/stations/AS_GAT",
    filters=[
        TimeFilter("submTime", ">", "2016-07-01T12:00:00Z"),
        TimeFilter("submTime", "<", "2018-07-10T12:00:00Z"),
        SizeFilter(">", 5000),
        SamplingHeightFilter("=", 216),
    ],
    include_deprecated=True,
    order_by="fileName",
    # limit = 50
)

filtered_atc_co2

[DataObjectLite(uri='https://meta.icos-cp.eu/objects/yGh8S2hyBa3xnD0KKq4zp3Ul', filename='ICOS_ATC_L2_L2pre2018.1_GAT_216.0_489_CO2.zip', size_bytes=130398, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2L2DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_GAT', sampling_height=216.0, submission_time=datetime.datetime(2018, 5, 23, 8, 12, 41, 724000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2017, 4, 11, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2017, 12, 31, 23, 0, tzinfo=datetime.timezone.utc))]

In [14]:
from icoscp_core.icos import meta

station_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"

# List ALL data objects associated with this station
dobjs = meta.list_data_objects(station=station_uri, limit=10000)

# Extract URIs
dobj_uris = [dobj.uri for dobj in dobjs]

fluxes_l2 = [d for d in dobjs if "FLUXES" in d.filename]

len(dobjs)

10000

In [15]:
dobjs = meta.list_data_objects(station=station_uri, limit=10000)
for d in dobjs:
    print(d.uri, d.filename)

https://meta.icos-cp.eu/objects/pWF4dPTeCkOtHzOC4r7E_jcx ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_70.0_1699-506_N2O.zip
https://meta.icos-cp.eu/objects/4qqbxxrG9F5t5ffQJGlMNuVp ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/LMt0jdvHh27L5OrCmCpJliwe ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/R4l3EVUQXvwt20mJNDUTkt1d ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/MeQT9hDnFTyWUchL44ezPipi ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_30.0_1699-506_N2O.zip
https://meta.icos-cp.eu/objects/kC_4RMBhiCCPWP08B99EsyCA ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/tYhMcQzPloss960OEd73PDFB ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/K-5EzUF_f8iNUXzAGOa2f1cT ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/RRpMkjeivgx6W4DGOSMshuec ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_150.0_1699-506_N2O.zip
https://meta.icos-cp.eu/objects/l53t_-Cnu9OXwl8omv7n24gr ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/TyHwC08Uc08WFL3bC-hAjYT1 ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/DgEIxrGB--pOc-yrsNDg23Vk ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/KxjPcRojljReSsM5K-Jj07HJ ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_613_MTO.zip
https://meta.icos-cp.eu/objects/3iA4ZFI-25eO04HbdHWtkUCI ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1778_MTO.zip
https://meta.icos-cp.eu/objects/xhjNQdXwyNqb8J6Kmv38Xgto ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_3.5_536_MTO.zip
https://meta.icos-cp.eu/objects/7MLuCj-F3t2ZshkLj1JgfUto ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1779_MTO.zip
https://meta.icos-cp.eu/objects/c9gtrFELoyID5dfK4BYdfnb9 HTM_1779_3_20260303.zip
https://meta.icos-cp.eu/objects/tB06mrgvUtABHXbxJNxkWAX0 HTM_1778_1_20260303.zip
https://meta.icos-cp.eu/objects/eoGHmgUge7ls-QTnKPYHFuAl HTM_613_2_20260303.zip
https://meta.icos-cp.eu/objects/x6iROy8AJXTFLtzFRdENhcTY HTM_536_4_20260303.zip
https://meta.icos-cp.eu/objects/G2zAEDeLyVEkoLYUlpKJjAto HTM_1238_20260303.zip
https://meta.icos-cp.eu/objects/cfBUx6LmzkdNDO_evceoQPqL HTM_506_20260303.zip
https://meta.icos-cp.eu/objects/jnXFR8x7Gec4J4tDSDbUQTYa ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/fuFgLT1n6mL2aTpZhY14waHO ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/90e0k-kmpZchB0HempIjt7hZ ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/IPBOUy_AKacG_kexhjS4SFct ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/PAyBdSmFf4M9Fqtqn4Qgc8lC ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/WKw-9ephBHVjWmWyjpxM0MEy ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/Fv9C95-cpl3xsE-pbb7un8k3 ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/tVllxF_pLCgjg4861AVba-Vn ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/k17ioyx9C4_3yFfBXRHNy_vF ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/LUi9octz2XoUXHkwUeD41PR1 HTM_1779_3_20260302.zip
https://meta.icos-cp.eu/objects/BfhSU0KECbCltmEdocyGPFlD HTM_1778_1_20260302.zip
https://meta.icos-cp.eu/objects/sJOpGer9AGNFWdJXVnwf0HON HTM_613_2_20260302.zip
https://meta.icos-cp.eu/objects/6aBb6aICQ6220D4ijwIgQSpT HTM_536_4_20260302.zip
https://meta.icos-cp.eu/objects/1aKaHk3_YfR8IsWuhNzXKrFB HTM_1238_20260302.zip
https://meta.icos-cp.eu/objects/h0FGWlbDTdQwVfHfXLrf22VQ HTM_506_20260302.zip
https://meta.icos-cp.eu/objects/kKnysMU0Ziaiv1rwOIhvpeN9 ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/ORqSGU38S42k12zBguDggz38 ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/Ew62t4zt2amASwHNJxHM9HeP ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/zOPIK45NFLLht5Db3_Dq00ta ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/_mWUO-Z-NIvLzkVOB0dbVOrN ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/AH7W_vbqoh1GjS1CXCfcZi_o ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/dDhdCn9JOPwOncLtx6AHUG1a ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/yxCkHnXvhWRkJrKIkByX3Kpq ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/-MPk0K-k3xQRQcVfSLRXOImU ICOS_ATC_NRT_HTM_2026-03-02_2026-03-02_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/8jCt4YuRRGCRonAJQGHbX_U7 HTM_1779_3_20260301.zip
https://meta.icos-cp.eu/objects/8gIzeBRQ1Prt3s2DlCkBnx8- HTM_1778_1_20260301.zip
https://meta.icos-cp.eu/objects/C95LrRHInjDn3po3JAPE5rz0 HTM_613_2_20260301.zip
https://meta.icos-cp.eu/objects/HVz7EOxoaIaRC9dIIOmSsArC HTM_536_4_20260301.zip
https://meta.icos-cp.eu/objects/Ta8osLQa1w_GXVlPDiZqT-tm HTM_506_20260301.zip
https://meta.icos-cp.eu/objects/d6wFGKI8nTXWSa9RUJV_STj4 ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/maFT1uoSrQB4tmxkogCkbhmp ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/nOtIo9uFUZtVvz-1XxnGiqNW ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/zTJC6sg4PMiP3tztFlAX74De ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/BcqrLdRcuWaOSkEGz0yY9rQm ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/r7PuEPcPkwQxAOFRawqcyA02 ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/8y04SJIss5cC6tmsBxmetGQW ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/lNau9Jrv34QA4Mg19iPZ7lut ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/erWfYy2s9IyK6sZqZvGTcPTh ICOS_ATC_NRT_HTM_2026-03-01_2026-03-01_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/NLf3f6AGmj-ZKQNHad32p9Hx HTM_1779_3_20260228.zip
https://meta.icos-cp.eu/objects/4tTGOJC9RQWzjoXc19Jrr5WE HTM_1778_1_20260228.zip
https://meta.icos-cp.eu/objects/yD-wx93xswegMPUfob7hPuiy HTM_613_2_20260228.zip
https://meta.icos-cp.eu/objects/CXAQclmjFXDo9caRZfrT6Jie HTM_536_4_20260228.zip
https://meta.icos-cp.eu/objects/-qL-DA3OsTzxzyeOumY-0eN- HTM_1238_20260228.zip
https://meta.icos-cp.eu/objects/7poqhy6BG4o_ocJ3Gf4-O-g7 HTM_506_20260228.zip
https://meta.icos-cp.eu/objects/1ulRP9EkiyrB1NkVCM5cqwIY ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/zBuSOirPf1txpL6WZGbIcVe6 ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/wGMd4U79YwyDVVfUy2d44jzA ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/ov6LKpp60YKYRnnPqP2LlTRP ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/B743eBNW9onBB_rOnrjuOF09 ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/XDjRlK884u6M20LfS8xcx4iU ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/wUtNcn3LVbGh72mPgfoS2GPD ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/fm0lTKr-UnEGN5HtKIcK_qKI ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/btEtc_Y3ClwUElv3ON-88i8F ICOS_ATC_NRT_HTM_2026-02-28_2026-02-28_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/eFZ7p5bRxRc38BmpZDDurKBR HTM_1779_3_20260227.zip
https://meta.icos-cp.eu/objects/l4J04Z5OoCV6zoBXtY25Bwlr HTM_1778_1_20260227.zip
https://meta.icos-cp.eu/objects/jrHrWtPfNcri0vxEcVcgYNVV HTM_613_2_20260227.zip
https://meta.icos-cp.eu/objects/sE72Uao1UBN2-HGe34TWAe1I HTM_536_4_20260227.zip
https://meta.icos-cp.eu/objects/IaxVHqmWz2PATSJJQuwsLdCc HTM_506_20260227.zip
https://meta.icos-cp.eu/objects/49fiv5uIsBexhXE4AYvmfgqh ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/wTsgpHssVSj2KB-74HVBdrCg ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/CtbkoPgwNqxid61i8xBKKk4B ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/MRgIzrycbvpT68SFX1RBhpTu ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/sFO3lbkOXS4VppjSdWUu1mqk ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/voivlMoKBIkzkqiKaMVLq9iE ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/Brf4mKxh--Lb1AOExL5w1vxO ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/p5TnEm0JgCJ6124_1uZmFMsz ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/8BIYcflVwHuMpWKjVjfxKoFv ICOS_ATC_NRT_HTM_2026-02-27_2026-02-27_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/FSuNnq76-0smR5uENYALbTp- HTM_1779_3_20260226.zip
https://meta.icos-cp.eu/objects/GvkJ9OtqqLHhDzaujIqap7s5 HTM_1778_1_20260226.zip
https://meta.icos-cp.eu/objects/RDgWEigpUDpyG1jEKK4g-_ZP HTM_613_2_20260226.zip
https://meta.icos-cp.eu/objects/u9DLirln1DMzTgpf03ikD309 HTM_536_4_20260226.zip
https://meta.icos-cp.eu/objects/4wqGoPTB-c0ks0M-NRsRgbv5 HTM_1238_20260226.zip
https://meta.icos-cp.eu/objects/3w7Jwycrp2lYXIQlTA5QmrRK HTM_506_20260226.zip
https://meta.icos-cp.eu/objects/Xyb52E1VfeicvA8gevjtQvxD ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/1Akk9nbr2gollHqkmumB603C ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/RNf9e70Gh0UAsWQrBWWyVal_ ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/NAfwo2eeWkuXwMzschXVg7h6 ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/1z22idCBMfRumBJbjN9r7sY3 ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/lIOCjPe_9b0XRz0U45UiOgjc ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/kzruXHzPeUxDJ62ACuMW7O0R ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/En9N9BUQOJiCMmfodHFLyRAt ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/Z9Shxow8zmmzh1VDBMt6p96x ICOS_ATC_NRT_HTM_2026-02-26_2026-02-26_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/6QY16k_3NJZpimFy1nK3bQGu HTM_1779_3_20260225.zip
https://meta.icos-cp.eu/objects/s-nBPuM-1BFJuiV1JCllEy0u HTM_1778_1_20260225.zip
https://meta.icos-cp.eu/objects/-i4osPj9Vd2R7TVdAogyNXq3 HTM_613_2_20260225.zip
https://meta.icos-cp.eu/objects/7pAtEvNZ2aqS4CLOEUOaHvED HTM_536_4_20260225.zip
https://meta.icos-cp.eu/objects/BB3KPwhe433KdQuD_40DtvCf HTM_1238_20260225.zip
https://meta.icos-cp.eu/objects/AsmkrsyU4ma2M5oe079AgEWQ HTM_506_20260225.zip
https://meta.icos-cp.eu/objects/6bfNnIW_dNU5xHmH8u0XyRni ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/l1_GRK87XsA4ny18qiyN0nhU ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/9AjeacOD4PaVMb4g54HG-Z71 ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/DCoCwPdwIjkmp1nMjYtkUm2- ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/BKGVkUChFB9L3bM_SfS__rR- ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/5DjCW4VbUR8muN6xx3EJZJDJ ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/JFZMCvW4Vz9iBEDrb5J8ThXT ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/gWTvtQ9K4EzlHP6X0tVKegCe ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/2IWPfcXPpLHT71FIDVNqKkIu ICOS_ATC_NRT_HTM_2026-02-25_2026-02-25_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/Umc-aJX-LBuvfwlgLGD0LoKJ HTM_1779_3_20260224.zip
https://meta.icos-cp.eu/objects/ynkIETr1hl9n1Sq6Hyw4tapv HTM_1778_1_20260224.zip
https://meta.icos-cp.eu/objects/oJVgisO8kISBpouME3MI4ZNd HTM_613_2_20260224.zip
https://meta.icos-cp.eu/objects/NexdpeKJZEqpULVM5m80mI2R HTM_536_4_20260224.zip
https://meta.icos-cp.eu/objects/WSJ3L1hcO0bBPnvagJ1phpv0 HTM_1238_20260224.zip
https://meta.icos-cp.eu/objects/ZJhYXEuKx3RFn2KiL2Zq0QUE HTM_506_20260224.zip
https://meta.icos-cp.eu/objects/rdhqarfytwIJtA-C_42Ufnzy ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/sMVIbUkHRBGXNCdZ9Ptb7Wnv ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/aUYK4Y0FsJWanvL12GzBUsUS ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/rC6cBw_ya58bAMu-zws76wIa ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/vIxzxQVuDHMHkY6CAFUL8MBA ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/gUzIa9mykCtb8KBQuT2RDNlm ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/_WyEObOUIq-5eXeq7RT49KyV ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/i2TVHo-N-h187QA5xyeGp6h6 ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/VKOeNm9GFmcB7758higx3VgA ICOS_ATC_NRT_HTM_2026-02-24_2026-02-24_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/yxXxqk9i4ht8KwTB90coCaTO HTM_1779_3_20260223.zip
https://meta.icos-cp.eu/objects/B29MkrVxJKwIIIDnG_K8rdaA HTM_1778_1_20260223.zip
https://meta.icos-cp.eu/objects/KS70oNPG4NIZ_XqmRRYJZb6b HTM_613_2_20260223.zip
https://meta.icos-cp.eu/objects/hJFP8Enan0ZKMBaBlrlMvLVt HTM_536_4_20260223.zip
https://meta.icos-cp.eu/objects/DqVNL1mz6GnwlzFKDFFIec3W HTM_1238_20260223.zip
https://meta.icos-cp.eu/objects/Y1ayorEXi56IIoS3uchzuC03 HTM_506_20260223.zip
https://meta.icos-cp.eu/objects/NOytcv8NlTdfxoYS3nRaFJqr ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/TkPxjHmGsu6Moz87j9vHg6UA ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/vtx0cSlPHVu46SIbSJEEWIBW ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_70.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/ILcACQcLUlJFpbwgT2nZmul7 ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/D7Q-lCyawfpzqG4eM0wiTvth ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/Tc4k0-cCulGcsLSTO71sJspA ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_30.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/gY6CjoopLQn7RLypp6rw1qft ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/QiEQbe0mwGooUNFMr4Fc0Iif ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/d0LUCo2fo_ja6c4-CycKkCae ICOS_ATC_NRT_HTM_2026-02-23_2026-02-23_150.0_1238-506_CO.zip
https://meta.icos-cp.eu/objects/yKd-Uq9Amti1C4UqxCPyIwF2 HTM_1779_3_20260222.zip
https://meta.icos-cp.eu/objects/RkleqWbtr8CfUU9TCPwiBOVR HTM_1779_3_20260221.zip
https://meta.icos-cp.eu/objects/pC8fAF0Y-4iLz_KVP-7g27Ny HTM_1778_1_20260222.zip
https://meta.icos-cp.eu/objects/ZTjHd8npD7yN1FRXumGHWFU0 HTM_1778_1_20260221.zip
https://meta.icos-cp.eu/objects/ALoSGxTp92imT4JhYovwl1N2 HTM_613_2_20260222.zip
https://meta.icos-cp.eu/objects/50FODVCgo2TlOdWSEipJjcaz HTM_613_2_20260221.zip
https://meta.icos-cp.eu/objects/JyFmJXGpUmsPwhIGTOrUZH_P HTM_536_4_20260222.zip
https://meta.icos-cp.eu/objects/JEmje4e6Q4F4jVD1bDcXhK8a HTM_536_4_20260221.zip
https://meta.icos-cp.eu/objects/uKB6BK_xwkoOALHVguMPkf8i HTM_506_20260222.zip
https://meta.icos-cp.eu/objects/D5fdomX6xhYXo-7TIR45ET6u ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/7IvTpWMVBwt_Kf4jZTIz7Pbk ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/rfRfEolSgO7d5L6X3S9fvFFp ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_70.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/uOQNqXX538ydUlU_c2lKYKJc ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/ojCKweuZOCnfycRtOvCJKGW_ ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/DQWMN-d3sxcW4POroVu-HJf8 ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_30.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/VTuYIzi-BRw5IepwyQRwN_Tm ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/lTHkZ9wWkowq15Plje3D8Uc9 ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/Ax4yxzQ5sSHPyEnH935DY1R6 ICOS_ATC_NRT_HTM_2026-02-22_2026-02-22_150.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/wOnpWiaf8g0NXX44f9g-7Dxx HTM_1238_20260221.zip
https://meta.icos-cp.eu/objects/XTnBnnEpv6pxLpSkEGjI6who HTM_506_20260221.zip
https://meta.icos-cp.eu/objects/2KYWBITIpyg5CrHTu9lFAuJg ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/dq89RA9XqVzMlHqfA2ow_fXc ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/-Dzr8B_To87WWqjinuwr0MfL ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_70.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/znKKDNPqdapBI6vPymw5rzKn ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/IyMU3N713dhtAcWspGTVLcAM ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/J8G3Q1fcLQM3d27WCTcEIuBN ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_30.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/zT663fMpH2UtbMiUW1Pz9cxh ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/wYAPI_5jcXi6D59wPu29lM3Q ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/K1WoXUefYmDV7ZCvDuM8A5xW ICOS_ATC_NRT_HTM_2026-02-21_2026-02-21_150.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/CSuxlFwyl0vpFOTjVP7bKwQ1 HTM_1779_3_20260220.zip
https://meta.icos-cp.eu/objects/JTS9SBDNPpqPSLAL3gf63D7A HTM_1778_1_20260220.zip
https://meta.icos-cp.eu/objects/LIZ6a_9mm6SBRT5mGyrYDqZR HTM_613_2_20260220.zip
https://meta.icos-cp.eu/objects/-qXdOvEUYKBcIFwcGOWr8QwY HTM_536_4_20260220.zip
https://meta.icos-cp.eu/objects/KQfhon1p3Y61PjcO-sjoM95K HTM_506_20260220.zip
https://meta.icos-cp.eu/objects/Rma_un_RTWFXy82sUN0_z5qU ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_70.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/WgZAUBSrvrg0U_QZ6j-1urQS ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_70.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/GQBK2jxga7GCYIle2gwE3Fb8 ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_70.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/clDZjfn54lH-AXrXUzqCogPB ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_30.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/x1skBC3OXcLU40AhLlw-T687 ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_30.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/BYmytdT6NE6pkjaTdx9PqfOs ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_30.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/s1KUEP2u_JIbOWBICY6P3zcK ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_150.0_1238_CO2.zip
https://meta.icos-cp.eu/objects/7OD6FRzrmJqN9_1m-AKesRtw ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_150.0_1238_CH4.zip
https://meta.icos-cp.eu/objects/GDtUXR8WNIgDZwLwS1hEgy4V ICOS_ATC_NRT_HTM_2026-02-20_2026-02-20_150.0_1238-1699-506_CO.zip
https://meta.icos-cp.eu/objects/o8269ozrkBA5Mg1a7SHJ3lr8 HTM_1779_3_20260219.zip
https://meta.icos-cp.eu/objects/fura5Nn3VpWF5Vr1JCP-aWxo HTM_1778_1_20260219.zip

In [16]:
from icoscp_core.icos import station_class_lookup

htm_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"
htm_class = station_class_lookup()[htm_uri]

htm_class

'1'

In [17]:
htm_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"
htm_station_meta = meta.get_station_meta(htm_uri)

htm_station_meta.__dict__

{'org': Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', label='HTM', comments=[]), name='Hyltemossa', email=None, website=None, webpageDetails=None),
 'id': 'HTM',
 'location': Position(lat=56.0976, lon=13.4189, alt=115.0, label='HTM', uri=None),
 'coverage': None,
 'responsibleOrganization': Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CEC', label='CEC', comments=[]), name='Centre for Environmental and Climate Science, Lund University', email=None, website='https://www.cec.lu.se', webpageDetails=None),
 'pictures': ['https://meta.icos-cp.eu/files/655_ISiY9jPRX2HHmCEW1_ux/Hyltemossa%202.JPG'],
 'specificInfo': AtcStationSpecifics(wigosId='0-20008-0-HTM', theme=DataTheme(self=UriResource(uri='http://meta.icos-cp.eu/resources/themes/atmosphere', label='Atmospheric data', comments=[]), icon='https://static.icos-cp.eu/images/themes/atm.svg', markerIcon='https://static.icos-cp.eu/share/stations/icons/as.png'), stationClass='1', labelingDate='2018-05-31', discontinued=False, timeZoneOffset=1, documentation=[PlainStaticObject(res='https://meta.icos-cp.eu/objects/FtAw9aAzcJWX2CdQ8rBwecOg', hash='FtAw9aAzcJWX2CdQ8rBwecOgYL37LfIj-Z-zBkOfOyQ', name='STILT station characterization for Hyltemossa at 150m')]),
 'countryCode': 'SE',
 'funding': None,
 'staff': [Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Tobias_Biermann', label=None, comments=[]), firstName='Tobias', lastName='Biermann', email='tobias.biermann@mgeo.lu.se', orcid='0000-0001-8538-1495'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/PI', label='Principal Investigator', comments=[]), start='2017-04-17T00:00:00Z', end=None, weight=20, extra=None)),
  Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Michal_Heliasz', label=None, comments=[]), firstName='Michal', lastName='Heliasz', email='michal.heliasz@mgeo.lu.se', orcid='0000-0003-2635-9604'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/PI', label='Principal Investigator', comments=[]), start='2017-04-17T00:00:00Z', end=None, weight=70, extra=None)),
  Membership(person=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Meelis_M%C3%B6lder', label=None, comments=[]), firstName='Meelis', lastName='Molder', email='meelis.molder@mgeo.lu.se', orcid='0000-0001-6767-3195'), role=RoleDetails(role=UriResource(uri='http://meta.icos-cp.eu/resources/roles/Engineer', label='Engineer', comments=[]), start='2017-04-17T00:00:00Z', end='2024-01-01T00:00:00Z', weight=None, extra=None))]}

In [18]:
from icoscp_core.icos import meta

station_uri = "http://meta.icos-cp.eu/resources/stations/AS_HTM"

all_objects = []
offset = 0
batch_size = 1000  # fetch 1000 at a time

while True:
    batch = meta.list_data_objects(station=station_uri, limit=batch_size, offset=offset)
    if not batch:
        break
    all_objects.extend(batch)
    offset += batch_size
    # print(f"Fetched {len(all_objects)} objects so far...")

print(f"Total objects fetched: {len(all_objects)}")

Total objects fetched: 35202

In [19]:
all_objects[0].__dict__

{'uri': 'https://meta.icos-cp.eu/objects/pWF4dPTeCkOtHzOC4r7E_jcx',
 'filename': 'ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_70.0_1699-506_N2O.zip',
 'size_bytes': 43380,
 'datatype_uri': 'http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject',
 'station_uri': 'http://meta.icos-cp.eu/resources/stations/AS_HTM',
 'sampling_height': 70.0,
 'submission_time': datetime.datetime(2026, 3, 4, 11, 9, 17, 527000, tzinfo=datetime.timezone.utc),
 'time_start': datetime.datetime(2025, 5, 19, 16, 0, tzinfo=datetime.timezone.utc),
 'time_end': datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)}

In [20]:
all_objects

[DataObjectLite(uri='https://meta.icos-cp.eu/objects/pWF4dPTeCkOtHzOC4r7E_jcx', filename='ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_70.0_1699-506_N2O.zip', size_bytes=43380, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 17, 527000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 5, 19, 16, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/4qqbxxrG9F5t5ffQJGlMNuVp', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238_CO2.zip', size_bytes=113014, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 16, 524000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/LMt0jdvHh27L5OrCmCpJliwe', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238_CH4.zip', size_bytes=113453, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 15, 414000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/R4l3EVUQXvwt20mJNDUTkt1d', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_1238-1699-506_CO.zip', size_bytes=115231, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 14, 153000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/MeQT9hDnFTyWUchL44ezPipi', filename='ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_30.0_1699-506_N2O.zip', size_bytes=43407, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 12, 761000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 5, 19, 16, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/kC_4RMBhiCCPWP08B99EsyCA', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238_CO2.zip', size_bytes=115680, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 11, 801000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/tYhMcQzPloss960OEd73PDFB', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238_CH4.zip', size_bytes=115800, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 10, 712000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/K-5EzUF_f8iNUXzAGOa2f1cT', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1238-1699-506_CO.zip', size_bytes=117178, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 9, 604000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/RRpMkjeivgx6W4DGOSMshuec', filename='ICOS_ATC_NRT_HTM_2025-05-19_2026-03-03_150.0_1699-506_N2O.zip', size_bytes=44705, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 7, 767000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 5, 19, 16, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/l53t_-Cnu9OXwl8omv7n24gr', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238_CO2.zip', size_bytes=115393, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 6, 765000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/TyHwC08Uc08WFL3bC-hAjYT1', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238_CH4.zip', size_bytes=116314, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 5, 620000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/DgEIxrGB--pOc-yrsNDg23Vk', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1238-1699-506_CO.zip', size_bytes=118542, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 11, 9, 4, 444000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/KxjPcRojljReSsM5K-Jj07HJ', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_70.0_613_MTO.zip', size_bytes=261279, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoGrowingNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 11, 5, 47, 117000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/3iA4ZFI-25eO04HbdHWtkUCI', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_30.0_1778_MTO.zip', size_bytes=272507, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoGrowingNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 11, 5, 45, 325000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/xhjNQdXwyNqb8J6Kmv38Xgto', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_3.5_536_MTO.zip', size_bytes=113861, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoGrowingNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=3.5, submission_time=datetime.datetime(2026, 3, 4, 11, 5, 43, 873000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/7MLuCj-F3t2ZshkLj1JgfUto', filename='ICOS_ATC_NRT_HTM_2025-04-01_2026-03-03_150.0_1779_MTO.zip', size_bytes=266304, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoGrowingNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 11, 5, 42, 465000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/c9gtrFELoyID5dfK4BYdfnb9', filename='HTM_1779_3_20260303.zip', size_bytes=17543, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 40, 24, 289000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/tB06mrgvUtABHXbxJNxkWAX0', filename='HTM_1778_1_20260303.zip', size_bytes=18203, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 40, 23, 578000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/eoGHmgUge7ls-QTnKPYHFuAl', filename='HTM_613_2_20260303.zip', size_bytes=18127, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 40, 22, 856000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/x6iROy8AJXTFLtzFRdENhcTY', filename='HTM_536_4_20260303.zip', size_bytes=6897, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 40, 22, 105000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/G2zAEDeLyVEkoLYUlpKJjAto', filename='HTM_1238_20260303.zip', size_bytes=11593071, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcPicarroL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 0, 35, 301000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 2, 23, 59, 59, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/cfBUx6LmzkdNDO_evceoQPqL', filename='HTM_506_20260303.zip', size_bytes=5440248, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcPicarroL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 4, 10, 0, 33, 666000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, 2, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 59, 58, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/jnXFR8x7Gec4J4tDSDbUQTYa', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238_CO2.zip', size_bytes=1858, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 50, 257000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/fuFgLT1n6mL2aTpZhY14waHO', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238_CH4.zip', size_bytes=1878, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 49, 336000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/90e0k-kmpZchB0HempIjt7hZ', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_70.0_1238-506_CO.zip', size_bytes=1901, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=70.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 48, 519000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/IPBOUy_AKacG_kexhjS4SFct', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238_CO2.zip', size_bytes=1885, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 47, 667000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/PAyBdSmFf4M9Fqtqn4Qgc8lC', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238_CH4.zip', size_bytes=1906, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 46, 888000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/WKw-9ephBHVjWmWyjpxM0MEy', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_30.0_1238-506_CO.zip', size_bytes=1911, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=30.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 45, 990000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/Fv9C95-cpl3xsE-pbb7un8k3', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238_CO2.zip', size_bytes=1874, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 45, 228000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/tVllxF_pLCgjg4861AVba-Vn', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238_CH4.zip', size_bytes=1889, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 44, 460000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/k17ioyx9C4_3yFfBXRHNy_vF', filename='ICOS_ATC_NRT_HTM_2026-03-03_2026-03-03_150.0_1238-506_CO.zip', size_bytes=1895, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=150.0, submission_time=datetime.datetime(2026, 3, 4, 6, 16, 43, 684000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 3, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/LUi9octz2XoUXHkwUeD41PR1', filename='HTM_1779_3_20260302.zip', size_bytes=16619, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 3, 10, 40, 29, 278000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 2, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 2, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/BfhSU0KECbCltmEdocyGPFlD', filename='HTM_1778_1_20260302.zip', size_bytes=16759, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 3, 10, 40, 28, 551000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 2, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 2, 23, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/sJOpGer9AGNFWdJXVnwf0HON', filename='HTM_613_2_20260302.zip', size_bytes=15976, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcMeteoL0DataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_HTM', sampling_height=None, submission_time=datetime.datetime(2026, 3, 3, 10, 40, 27, 704000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2026, 3, 2, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 2, 23, 59, tzinfo=datetime.timezone.utc)),

In [21]:
from icoscp_core.icos import meta

# List all data objects (returns DobjSpecLite objects)
all_objects = meta.list_data_objects()

# Extract URIs in the exact format you want
all_uris = [dobj.uri for dobj in all_objects]

# Inspect
len(all_uris), all_uris[:5]

(100,
 ['https://meta.icos-cp.eu/objects/Gyy707SMePiDDlFUCt8Du2Cq',
  'https://meta.icos-cp.eu/objects/uI-KaooRRgyJcWY_EM56UwI8',
  'https://meta.icos-cp.eu/objects/pdQm19rCVUsRdeaw1-GvO_QK',
  'https://meta.icos-cp.eu/objects/IFM7oxedUOnnMSdhU_zP90-c',
  'https://meta.icos-cp.eu/objects/YVlnWJlU7i2kUwX7japQ6W42'])

In [22]:
all_objects

[DataObjectLite(uri='https://meta.icos-cp.eu/objects/Gyy707SMePiDDlFUCt8Du2Cq', filename='n2o_isotopes_and_fluxes_agroscope_reckenholz_PARIS.zip', size_bytes=815408, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/genericDataArchiveL2', station_uri='http://meta.icos-cp.eu/resources/stations/Reckenholz', sampling_height=None, submission_time=datetime.datetime(2026, 5, 31, 23, 59, 59, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2024, 3, 5, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2024, 12, 11, 23, 59, 59, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/uI-KaooRRgyJcWY_EM56UwI8', filename='PARIS_WP3_F-GAS_obs_2025-07-04.zip', size_bytes=380017039, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atmoMeasArchive', station_uri=None, sampling_height=None, submission_time=datetime.datetime(2026, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(1987, 1, 23, 13, 57, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/pdQm19rCVUsRdeaw1-GvO_QK', filename='ICOS_ATC_NRT_ZSF_2025-04-01_2026-03-03_3.0_1482_N2O.zip', size_bytes=97715, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZSF', sampling_height=3.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 33, 622000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/IFM7oxedUOnnMSdhU_zP90-c', filename='ICOS_ATC_NRT_ZSF_2025-04-01_2026-03-03_3.0_1167_CO2.zip', size_bytes=108853, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZSF', sampling_height=3.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 32, 536000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/YVlnWJlU7i2kUwX7japQ6W42', filename='ICOS_ATC_NRT_ZSF_2025-04-01_2026-03-03_3.0_1167_CH4.zip', size_bytes=113552, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZSF', sampling_height=3.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 31, 265000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/g9EQHJVWB9Qb770rvi6-V6i7', filename='ICOS_ATC_NRT_ZSF_2025-04-01_2026-03-03_3.0_1167-1482_CO.zip', size_bytes=118567, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZSF', sampling_height=3.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 30, 235000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/BrwE9R3oRGBkQ-FPV8uchVs_', filename='ICOS_ATC_NRT_ZEP_2025-04-01_2026-03-03_15.0_1272_CO2.zip', size_bytes=98289, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZEP', sampling_height=15.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 28, 984000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/52F1UR3BXzrAGqh9s2W2I6LV', filename='ICOS_ATC_NRT_ZEP_2025-04-01_2026-03-03_15.0_1272_CO.zip', size_bytes=105105, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZEP', sampling_height=15.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 27, 861000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/TDkNsv5wxMu4JxdxUARaescc', filename='ICOS_ATC_NRT_ZEP_2025-04-01_2026-03-03_15.0_1272_CH4.zip', size_bytes=103697, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_ZEP', sampling_height=15.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 26, 116000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/P0Ft1DtvOfAc10TkDyaRwtun', filename='ICOS_ATC_NRT_WES_2025-04-01_2026-03-03_14.0_1153_CO2.zip', size_bytes=109373, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WES', sampling_height=14.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 24, 954000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/xsmGrb2khMurJIXxGaik5UGz', filename='ICOS_ATC_NRT_WES_2025-04-01_2026-03-03_14.0_1153_CH4.zip', size_bytes=115213, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WES', sampling_height=14.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 23, 449000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/5KuTsl4nOm3lbnLdeIqn5mL_', filename='ICOS_ATC_NRT_WAO_2025-04-01_2026-03-03_10.0_505_N2O.zip', size_bytes=103046, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WAO', sampling_height=10.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 19, 205000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/ZVn7ieHGuuakIHMiDNaIjKzQ', filename='ICOS_ATC_NRT_WAO_2025-04-01_2026-03-03_10.0_505_CO.zip', size_bytes=117822, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WAO', sampling_height=10.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 16, 399000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/Xez-trquzdLuFy7-gE3xORj3', filename='ICOS_ATC_NRT_WAO_2025-04-01_2026-03-03_10.0_1400-505_CO2.zip', size_bytes=116958, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WAO', sampling_height=10.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 15, 216000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/r8jVnRVRdpWB9ZcTLtM192GH', filename='ICOS_ATC_NRT_WAO_2025-04-01_2026-03-03_10.0_1400-505_CH4.zip', size_bytes=119782, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_WAO', sampling_height=10.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 13, 637000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/fnjc6MIb8pY5kd70jHKxnfww', filename='ICOS_ATC_NRT_UTO_2025-04-01_2026-03-03_57.0_999_CO2.zip', size_bytes=105474, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_UTO', sampling_height=57.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 12, 248000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/JynDJkOtf9190v3MRZu6QxCK', filename='ICOS_ATC_NRT_UTO_2025-04-01_2026-03-03_57.0_999_CO.zip', size_bytes=108864, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_UTO', sampling_height=57.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 10, 679000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/jQWHa0l3FjgG1CIWk531ewZ1', filename='ICOS_ATC_NRT_UTO_2025-04-01_2026-03-03_57.0_999_CH4.zip', size_bytes=108081, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_UTO', sampling_height=57.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 9, 554000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/VGXKcU9GGowhKhBq-G_PbTmr', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_50.0_701_N2O.zip', size_bytes=92171, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=50.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 8, 195000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/7hyCu4_x26pZ1aiUgQgS_-HK', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_50.0_701-472_CO.zip', size_bytes=103483, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=50.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 6, 898000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/yhR1HtLhPXZXCa7e41QCripc', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_50.0_472_CO2.zip', size_bytes=98627, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=50.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 5, 463000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/A0IovQb23iBV1ivmra41m92S', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_50.0_472_CH4.zip', size_bytes=98851, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=50.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 4, 245000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/25vtcUGJEGNeZ5znTvMeK5Ci', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_5.0_701_N2O.zip', size_bytes=93753, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=5.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 3, 26000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/UCM55YuyYTvEHDPeb71wN943', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_5.0_701-472_CO.zip', size_bytes=104908, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=5.0, submission_time=datetime.datetime(2026, 3, 4, 11, 15, 1, 836000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/KIqO3eFfM26tEw1WarWfrh9R', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_5.0_472_CO2.zip', size_bytes=101121, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=5.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 58, 999000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/JeSMMdpSrxKKv65Hvsq9yhzb', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_5.0_472_CH4.zip', size_bytes=99326, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=5.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 57, 166000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/MaygtJzRcyA70WcuPLdUNZMf', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_180.0_701_N2O.zip', size_bytes=105080, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=180.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 55, 516000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/_40fN_emsaYcjkZaASp7zIwv', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_180.0_701-472_CO.zip', size_bytes=123108, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=180.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 54, 430000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/j1KdlAar43exn4Tc10RyYCnP', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_180.0_472_CO2.zip', size_bytes=116187, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=180.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 53, 120000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/VU0D7zknaBvj2DLfDwbiCKVq', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_180.0_472_CH4.zip', size_bytes=117471, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=180.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 51, 739000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/EB2OhFgg41fDi8s0LVWL36bZ', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_100.0_701_N2O.zip', size_bytes=93130, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcN2oNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=100.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 50, 567000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/JTCtUvDSgQqDuqzOlWoKIpb6', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_100.0_701-472_CO.zip', size_bytes=104596, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCoNrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=100.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 49, 566000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/XyJWYq3_G3rwdv9O4J3Lt9hw', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_100.0_472_CO2.zip', size_bytes=98836, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCo2NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=100.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 48, 465000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),
 DataObjectLite(uri='https://meta.icos-cp.eu/objects/YQdXqXtLgEvI1lrKjqOC3rt0', filename='ICOS_ATC_NRT_TRN_2025-04-01_2026-03-03_100.0_472_CH4.zip', size_bytes=98847, datatype_uri='http://meta.icos-cp.eu/resources/cpmeta/atcCh4NrtGrowingDataObject', station_uri='http://meta.icos-cp.eu/resources/stations/AS_TRN', sampling_height=100.0, submission_time=datetime.datetime(2026, 3, 4, 11, 14, 47, 374000, tzinfo=datetime.timezone.utc), time_start=datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), time_end=datetime.datetime(2026, 3, 3, 23, 0, tzinfo=datetime.timezone.utc)),

In [23]:
all_objects[0].datatype_uri

'http://meta.icos-cp.eu/resources/cpmeta/genericDataArchiveL2'

In [24]:
dobj_uris = [
    "https://meta.icos-cp.eu/objects/E2MVHezJQReXShfzPtBVlVwS",
    "https://meta.icos-cp.eu/objects/udtdN1NfB3YNvclaEm5RpbCd",
]

# dobj_uris = ["https://meta.icos-cp.eu/objects/wFrOPLqm3CcOZpUmxfbPTGqo"]

folder_path = "../data/raw/ICOS/"

unsucessful_count = 0

for idx, dobj_uri in enumerate(meteorological_urls[0:1]):
    try:
        filename = data.save_to_folder(dobj_uri, folder_path)

        zip_file_path = os.path.join(folder_path, filename)
        print(filename, zip_file_path, zip_file_path[:-4])

        # Extract the ZIP file
        with zipfile.ZipFile(zip_file_path, "r") as zip_ref:
            zip_ref.extractall(folder_path)

    except Exception as e:
        print(f"Error downloading file: {e} ----- {idx}----- {dobj_uri}")

ICOSETC_BE-Bra_METEOSENS_L2.zip ../data/raw/ICOS/ICOSETC_BE-Bra_METEOSENS_L2.zip ../data/raw/ICOS/ICOSETC_BE-Bra_METEOSENS_L2

In [25]:
meteorological_urls[0]

'https://meta.icos-cp.eu/objects/5PxQWHuF4f6dtvXiHU3G0hOF'

In [26]:
dobj = meta.get_dobj_meta("https://meta.icos-cp.eu/objects/hujSGCfmNIRdxtOcEvEJLxGM")
coll_info = dobj.parentCollections[0]
coll_label = coll_info.label
coll_2010 = meta.get_collection_meta(coll_info.uri)
coll_evapo_info = coll_2010.parentCollections[0]
coll_evapo = meta.get_collection_meta(coll_evapo_info.uri)
evapo_years = coll_evapo.members
top_coll_info = coll_evapo.parentCollections[0]
top_coll = meta.get_collection_meta(top_coll_info.uri)
top_subcols = top_coll.members

In [27]:
dobj.__dict__

{'hash': 'hujSGCfmNIRdxtOcEvEJLxGMQwyJG4kI7FSkotuXjqw',
 'accessUrl': 'https://data.icos-cp.eu/objects/hujSGCfmNIRdxtOcEvEJLxGM',
 'pid': '11676/hujSGCfmNIRdxtOcEvEJLxGM',
 'doi': '10.18160/5NZG-JMJE',
 'fileName': 'ET_2010_025_daily.nc',
 'size': 363256131,
 'submission': DataSubmission(submitter=Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CP', label='CP', comments=[]), name='Carbon Portal', email=None, website=None, webpageDetails=None), start='2024-01-30T13:18:04.251759Z', stop='2024-01-30T13:25:19.875259Z'),
 'specification': DataObjectSpec(self=UriResource(uri='http://meta.icos-cp.eu/resources/cpmeta/bioModelSpatialFLUXCOM', label='Biosphere-Modeling spatial results (FLUXCOM)', comments=['Set up for FLUXCOM model outputs']), project=Project(self=UriResource(uri='http://meta.icos-cp.eu/resources/projects/misc', label='Miscellaneous', comments=['Various other data not associated with a specific project']), keywords=None), theme=DataTheme(self=UriResource(uri='http://meta.icos-cp.eu/resources/themes/ecosystem', label='Ecosystem data', comments=[]), icon='https://static.icos-cp.eu/images/themes/eco.svg', markerIcon='https://static.icos-cp.eu/share/stations/icons/es.png'), format=ObjectFormat(self=UriResource(uri='http://meta.icos-cp.eu/ontologies/cpmeta/netcdf', label='NetCDF (spatial)', comments=[]), goodFlagValues=None), encoding=UriResource(uri='http://meta.icos-cp.eu/ontologies/cpmeta/plainFileEncoding', label='plain file', comments=[]), dataLevel=3, specificDatasetType='SpatioTemporal', datasetSpec=DatasetSpec(self=UriResource(uri='http://meta.icos-cp.eu/resources/cpmeta/bioModelSpatialDataFLUXCOM', label='Biosphere-Modeling spatial dataset (FLUXCOM)', comments=['To be used for FLUXCOM and FLUXCOM-X products']), resolution=None), documentation=[], keywords=['biosphere modeling']),
 'specificInfo': SpatioTemporalMeta(title='FLUXCOM-X daily evapotranspiration on global 0.25 degree grid for 2010', description='X-BASE ET is based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce this global product. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorlogical data, plant functional type classification as well as MODIS based vegitation indicies and land surface temperature. XGBoost was used as the machine learning algorithm. The GPP estimates from the eddy covariance data was based on the Nighttime Partitioning method.\n\nPublished paper: https://egusphere.copernicus.org/preprints/2024/egusphere-2024-165/', spatial=LatLonBox(min=Position(lat=-90.0, lon=-180.0, alt=None, label=None, uri=None), max=Position(lat=90.0, lon=180.0, alt=None, label=None, uri=None), label='Global lat/lon box', uri='http://meta.icos-cp.eu/resources/latlonboxes/globalLatLonBox'), temporal=TemporalCoverage(interval=TimeInterval(start='2010-01-01T00:00:00Z', stop='2010-12-31T00:00:00Z'), resolution='daily'), station=None, samplingHeight=None, productionInfo=DataProduction(creator=Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Ulrich_Weber', label=None, comments=[]), firstName='Ulrich', lastName='Weber', email=None, orcid='0000-0001-7116-035X'), contributors=[Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Gregory_Duveiller', label=None, comments=[]), firstName='Gregory', lastName='Duveiller', email='gduveiller@bgc-jena.mpg.de', orcid='0000-0002-6471-8404'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Fabian_Gans', label=None, comments=[]), firstName='Fabian', lastName='Gans', email='fgans@bgc-jena.mpg.de', orcid='0000-0001-9614-0435'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Zayd_Hamdi', label=None, comments=[]), firstName='Zayd', lastName='Hamdi', email='zmhamdi@bgc-jena.mpg.de', orcid='0000-0003-1658-8243'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Martin_Jung', label=None, comments=[]), firstName='Martin', lastName='Jung', email='mjung@bgc-jena.mpg.de', orcid=None), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Basil_Kraft', label=None, comments=[]), firstName='Basil', lastName='Kraft', email='bkraft@bgc-jena.mpg.de', orcid='0000-0002-8491-2730'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Jacob_Nelson', label=None, comments=[]), firstName='Jacob A.', lastName='Nelson', email='jnelson@bgc-jena.mpg.de', orcid='0000-0002-4663-2420'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Sophia_Walther', label=None, comments=[]), firstName='Sophia', lastName='Walther', email='swalth@bgc-jena.mpg.de', orcid='0000-0003-1681-9304'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Ulrich_Weber', label=None, comments=[]), firstName='Ulrich', lastName='Weber', email=None, orcid='0000-0001-7116-035X'), Person(self=UriResource(uri='http://meta.icos-cp.eu/resources/people/Weijie_Zhang', label='', comments=[]), firstName='Weijie', lastName='Zhang', email='wzhang@bgc-jena.mpg.de', orcid=None)], host=Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/MPI-BGC', label='MPI-BGC', comments=[]), name='Max Planck Institute for Biogeochemistry', email=None, website='https://www.bgc-jena.mpg.de/mpg/websiteBiogeochemie', webpageDetails=None), comment=None, sources=[], documentation=None, dateTime='2023-11-10T11:00:00Z'), variables=[VarMeta(model=UriResource(uri='http://meta.icos-cp.eu/resources/cpmeta/ET', label='ET', comments=['Evapotranspiration in  [mm h-1], used by FLUXCOM-X']), label='ET', valueType=ValueType(self=UriResource(uri='http://meta.icos-cp.eu/resources/cpmeta/evapotranspiration', label='evapotranspiration', comments=[]), quantityKind=UriResource(uri='http://meta.icos-cp.eu/resources/cpmeta/particleFlux', label='particle flux', comments=['amount of particles passing through unit area during unit of time']), unit='mm h-1'), valueFormat=None, isFlagFor=None, minMax=(-0.0074389479123055935, 0.4150887429714203), instrumentDeployments=None)]),
 'previousVersion': 'https://meta.icos-cp.eu/objects/BGQl9Sc9ziuZDfwrkFiZ9B8c',
 'nextVersion': None,
 'latestVersion': 'https://meta.icos-cp.eu/objects/hujSGCfmNIRdxtOcEvEJLxGM',
 'parentCollections': [UriResource(uri='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', label='FLUXCOM-X-BASE evapotranspiration for 2010', comments=[])],

In [28]:
dobj.parentCollections

[UriResource(uri='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', label='FLUXCOM-X-BASE evapotranspiration for 2010', comments=[])]

In [29]:
dobj.parentCollections[0]

UriResource(uri='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', label='FLUXCOM-X-BASE evapotranspiration for 2010', comments=[])

In [30]:
meta.get_collection_meta(dobj.parentCollections[0].uri)

StaticCollection(res='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', hash='_Sno9zc_18Oy3nwaKD-ZYUPO', members=[PlainStaticObject(res='https://meta.icos-cp.eu/objects/hujSGCfmNIRdxtOcEvEJLxGM', hash='hujSGCfmNIRdxtOcEvEJLxGMQwyJG4kI7FSkotuXjqw', name='FLUXCOM-X daily evapotranspiration on global 0.25 degree grid for 2010'), PlainStaticObject(res='https://meta.icos-cp.eu/objects/8T05NeB2GVeZmvO_FfrDK2tQ', hash='8T05NeB2GVeZmvO_FfrDK2tQj_O0L91sv_KUJzDVUT4', name='FLUXCOM-X monthly diurnal cycle of evapotranspiration on global 0.25 degree grid for 2010'), PlainStaticObject(res='https://meta.icos-cp.eu/objects/9wY9BgrGDX2smpBxUd7kvTtR', hash='9wY9BgrGDX2smpBxUd7kvTtRFl2SjDebD3lqBVg43tQ', name='FLUXCOM-X monthly evapotranspiration on global 0.05 degree grid for 2010'), PlainStaticObject(res='https://meta.icos-cp.eu/objects/7SOLdmdcpCDcdJN_rw0XDNu6', hash='7SOLdmdcpCDcdJN_rw0XDNu67fzaSmbJiPNThNG9rZg', name='FLUXCOM-X monthly evapotranspiration on global 0.5 degree grid for 2010')], creator=Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CP', label='CP', comments=[]), name='Carbon Portal', email=None, website=None, webpageDetails=None), title='FLUXCOM-X-BASE evapotranspiration for 2010', description='This compilation comprises four datasets showcasing evapotranspiration dynamics for the 2010 within the FLUXCOM-X framework. Derived from machine learning models trained on in-situ eddy covariance data, these datasets offer comprehensive insights into global evapotranspiration patterns. The X-BASE experiment, fundamental to FLUXCOM-X, incorporates core meteorological data, plant functional type classification, MODIS-based vegetation indices, and land surface temperature as predictors. Employing the XGBoost algorithm, these datasets provide estimations of evapotranspiration, utilizing the Nighttime Partitioning method for Gross Primary Productivity (GPP) estimates.', previousVersion=None, nextVersion=None, latestVersion='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', parentCollections=[UriResource(uri='https://meta.icos-cp.eu/collections/_l85vWiIV81AifoxCkty50YI', label='FLUXCOM-X-BASE evapotranspiration for 2001-2021', comments=[])], doi='10.18160/5NZG-JMJE', coverage=FeatureCollectionWithGeo(geo={'features': ({'geometry': {'coordinates': ([[-180.0, -90.0], [-180.0, 90.0], [180.0, 90.0], [180.0, -90.0], [-180.0, -90.0]],), 'type': 'Polygon'}, 'properties': {'label': 'Global lat/lon box'}, 'type': 'Feature'},), 'type': 'FeatureCollection'}, features=[LatLonBox(min=Position(lat=-90.0, lon=-180.0, alt=None, label=None, uri=None), max=Position(lat=90.0, lon=180.0, alt=None, label=None, uri=None), label='Global lat/lon box', uri=None)], label=None, uri=None), documentation=None, references=References(citationString='Nelson, J.A., Walther, S., Jung, M., Gans, F., Kraft, B., Weber, U., Hamdi, Z., Duveiller, G., Zhang, W., 2023. FLUXCOM-X-BASE. https://doi.org/10.18160/5NZG-JMJE', citationBibTex='@misc{https://doi.org/10.18160/5nzg-jmje,\n  doi = {10.18160/5NZG-JMJE},\n  url = {https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T},\n  author = {Nelson, Jacob A. and Walther, Sophia and Jung, Martin and Gans, Fabian and Kraft, Basil and Weber, Ulrich and Hamdi, Zayd and Duveiller, Gregory and Zhang, Weijie},\n  keywords = {BIOGEOCHEMICAL CYCLES, CARBON, ECOSYSTEM FUNCTIONS, FLUXCOM, LAND SURFACE, TERRESTRIAL ECOSYSTEMS, VEGETATION, biosphere modeling, carbon flux, FLUXCOM-X},\n  title = {FLUXCOM-X-BASE},\n  publisher = {ICOS ERIC -- Carbon Portal},\n  year = {2023},\n  copyright = {Creative Commons Attribution 4.0 International}\n}', citationRis="TY  - DATA\r\nT1  - FLUXCOM-X-BASE\r\nAU  - Nelson, Jacob A.\r\nAU  - Walther, Sophia\r\nAU  - Jung, Martin\r\nAU  - Gans, Fabian\r\nAU  - Kraft, Basil\r\nAU  - Weber, Ulrich\r\nAU  - Hamdi, Zayd\r\nAU  - Duveiller, Gregory\r\nAU  - Zhang, Weijie\r\nDO  - 10.18160/5NZG-JMJE\r\nUR  - https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T\r\nAB  - The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. \r\nKW  - BIOGEOCHEMICAL CYCLES\r\nKW  - CARBON\r\nKW  - ECOSYSTEM FUNCTIONS\r\nKW  - FLUXCOM\r\nKW  - LAND SURFACE\r\nKW  - TERRESTRIAL ECOSYSTEMS\r\nKW  - VEGETATION\r\nKW  - biosphere modeling\r\nKW  - carbon flux\r\nKW  - FLUXCOM-X\r\nPY  - 2023\r\nPB  - ICOS ERIC -- Carbon Portal\r\nER  -", doi={'contributors': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'creators': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'dates': (), 'descriptions': ({'description': "The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. ", 'descriptionType': 'Abstract'},), 'doi': '10.18160/5NZG-JMJE', 'formats': ('NetCDF (spatial)',), 'fundingReferences': (), 'geoLocations': ({'geoLocationBox': {'eastBoundLongitude': 180.0, 'northBoundLatitude': 90.0, 'southBoundLatitude': -90.0, 'westBoundLongitude': -180.0}, 'geoLocationPlace': 'Global lat/lon box'},), 'publicationYear': 2023, 'publisher': 'ICOS ERIC -- Carbon Portal', 'rightsList': ({'rights': 'Creative Commons Attribution 4.0 International', 'rightsUri': 'https://creativecommons.org/licenses/by/4.0/legalcode'},), 'state': 'findable', 'subjects': ({'subject': 'BIOGEOCHEMICAL CYCLES'}, {'subject': 'CARBON'}, {'subject': 'ECOSYSTEM FUNCTIONS'}, {'subject': 'FLUXCOM'}, {'subject': 'LAND SURFACE'}, {'subject': 'TERRESTRIAL ECOSYSTEMS'}, {'subject': 'VEGETATION'}, {'subject': 'biosphere modeling'}, {'subject': 'carbon flux'}, {'subject': 'FLUXCOM-X'}), 'titles': ({'lang': 'en-us', 'title': 'FLUXCOM-X-BASE'}, {'lang': 'en-us', 'title': 'X-BASE', 'titleType': 'AlternativeTitle'}), 'types': {'resourceType': 'netcdf', 'resourceTypeGeneral': 'Dataset'}, 'url': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T', 'version': '1.0'}, keywords=None, authors=None, title='FLUXCOM-X-BASE evapotranspiration for 2010', temporalCoverageDisplay=None, acknowledgements=None, licence=None))

In [31]:
coll_2010 = meta.get_collection_meta(dobj.parentCollections[0].uri)

coll_2010.__dict__

{'res': 'https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO',
 'hash': '_Sno9zc_18Oy3nwaKD-ZYUPO',
 'members': [PlainStaticObject(res='https://meta.icos-cp.eu/objects/hujSGCfmNIRdxtOcEvEJLxGM', hash='hujSGCfmNIRdxtOcEvEJLxGMQwyJG4kI7FSkotuXjqw', name='FLUXCOM-X daily evapotranspiration on global 0.25 degree grid for 2010'),
  PlainStaticObject(res='https://meta.icos-cp.eu/objects/8T05NeB2GVeZmvO_FfrDK2tQ', hash='8T05NeB2GVeZmvO_FfrDK2tQj_O0L91sv_KUJzDVUT4', name='FLUXCOM-X monthly diurnal cycle of evapotranspiration on global 0.25 degree grid for 2010'),
  PlainStaticObject(res='https://meta.icos-cp.eu/objects/9wY9BgrGDX2smpBxUd7kvTtR', hash='9wY9BgrGDX2smpBxUd7kvTtRFl2SjDebD3lqBVg43tQ', name='FLUXCOM-X monthly evapotranspiration on global 0.05 degree grid for 2010'),
  PlainStaticObject(res='https://meta.icos-cp.eu/objects/7SOLdmdcpCDcdJN_rw0XDNu6', hash='7SOLdmdcpCDcdJN_rw0XDNu67fzaSmbJiPNThNG9rZg', name='FLUXCOM-X monthly evapotranspiration on global 0.5 degree grid for 2010')],
 'creator': Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CP', label='CP', comments=[]), name='Carbon Portal', email=None, website=None, webpageDetails=None),
 'title': 'FLUXCOM-X-BASE evapotranspiration for 2010',
 'description': 'This compilation comprises four datasets showcasing evapotranspiration dynamics for the 2010 within the FLUXCOM-X framework. Derived from machine learning models trained on in-situ eddy covariance data, these datasets offer comprehensive insights into global evapotranspiration patterns. The X-BASE experiment, fundamental to FLUXCOM-X, incorporates core meteorological data, plant functional type classification, MODIS-based vegetation indices, and land surface temperature as predictors. Employing the XGBoost algorithm, these datasets provide estimations of evapotranspiration, utilizing the Nighttime Partitioning method for Gross Primary Productivity (GPP) estimates.',
 'previousVersion': None,
 'nextVersion': None,
 'latestVersion': 'https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO',
 'parentCollections': [UriResource(uri='https://meta.icos-cp.eu/collections/_l85vWiIV81AifoxCkty50YI', label='FLUXCOM-X-BASE evapotranspiration for 2001-2021', comments=[])],
 'doi': '10.18160/5NZG-JMJE',
 'coverage': FeatureCollectionWithGeo(geo={'features': ({'geometry': {'coordinates': ([[-180.0, -90.0], [-180.0, 90.0], [180.0, 90.0], [180.0, -90.0], [-180.0, -90.0]],), 'type': 'Polygon'}, 'properties': {'label': 'Global lat/lon box'}, 'type': 'Feature'},), 'type': 'FeatureCollection'}, features=[LatLonBox(min=Position(lat=-90.0, lon=-180.0, alt=None, label=None, uri=None), max=Position(lat=90.0, lon=180.0, alt=None, label=None, uri=None), label='Global lat/lon box', uri=None)], label=None, uri=None),
 'documentation': None,
 'references': References(citationString='Nelson, J.A., Walther, S., Jung, M., Gans, F., Kraft, B., Weber, U., Hamdi, Z., Duveiller, G., Zhang, W., 2023. FLUXCOM-X-BASE. https://doi.org/10.18160/5NZG-JMJE', citationBibTex='@misc{https://doi.org/10.18160/5nzg-jmje,\n  doi = {10.18160/5NZG-JMJE},\n  url = {https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T},\n  author = {Nelson, Jacob A. and Walther, Sophia and Jung, Martin and Gans, Fabian and Kraft, Basil and Weber, Ulrich and Hamdi, Zayd and Duveiller, Gregory and Zhang, Weijie},\n  keywords = {BIOGEOCHEMICAL CYCLES, CARBON, ECOSYSTEM FUNCTIONS, FLUXCOM, LAND SURFACE, TERRESTRIAL ECOSYSTEMS, VEGETATION, biosphere modeling, carbon flux, FLUXCOM-X},\n  title = {FLUXCOM-X-BASE},\n  publisher = {ICOS ERIC -- Carbon Portal},\n  year = {2023},\n  copyright = {Creative Commons Attribution 4.0 International}\n}', citationRis="TY  - DATA\r\nT1  - FLUXCOM-X-BASE\r\nAU  - Nelson, Jacob A.\r\nAU  - Walther, Sophia\r\nAU  - Jung, Martin\r\nAU  - Gans, Fabian\r\nAU  - Kraft, Basil\r\nAU  - Weber, Ulrich\r\nAU  - Hamdi, Zayd\r\nAU  - Duveiller, Gregory\r\nAU  - Zhang, Weijie\r\nDO  - 10.18160/5NZG-JMJE\r\nUR  - https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T\r\nAB  - The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. \r\nKW  - BIOGEOCHEMICAL CYCLES\r\nKW  - CARBON\r\nKW  - ECOSYSTEM FUNCTIONS\r\nKW  - FLUXCOM\r\nKW  - LAND SURFACE\r\nKW  - TERRESTRIAL ECOSYSTEMS\r\nKW  - VEGETATION\r\nKW  - biosphere modeling\r\nKW  - carbon flux\r\nKW  - FLUXCOM-X\r\nPY  - 2023\r\nPB  - ICOS ERIC -- Carbon Portal\r\nER  -", doi={'contributors': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'creators': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'dates': (), 'descriptions': ({'description': "The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. ", 'descriptionType': 'Abstract'},), 'doi': '10.18160/5NZG-JMJE', 'formats': ('NetCDF (spatial)',), 'fundingReferences': (), 'geoLocations': ({'geoLocationBox': {'eastBoundLongitude': 180.0, 'northBoundLatitude': 90.0, 'southBoundLatitude': -90.0, 'westBoundLongitude': -180.0}, 'geoLocationPlace': 'Global lat/lon box'},), 'publicationYear': 2023, 'publisher': 'ICOS ERIC -- Carbon Portal', 'rightsList': ({'rights': 'Creative Commons Attribution 4.0 International', 'rightsUri': 'https://creativecommons.org/licenses/by/4.0/legalcode'},), 'state': 'findable', 'subjects': ({'subject': 'BIOGEOCHEMICAL CYCLES'}, {'subject': 'CARBON'}, {'subject': 'ECOSYSTEM FUNCTIONS'}, {'subject': 'FLUXCOM'}, {'subject': 'LAND SURFACE'}, {'subject': 'TERRESTRIAL ECOSYSTEMS'}, {'subject': 'VEGETATION'}, {'subject': 'biosphere modeling'}, {'subject': 'carbon flux'}, {'subject': 'FLUXCOM-X'}), 'titles': ({'lang': 'en-us', 'title': 'FLUXCOM-X-BASE'}, {'lang': 'en-us', 'title': 'X-BASE', 'titleType': 'AlternativeTitle'}), 'types': {'resourceType': 'netcdf', 'resourceTypeGeneral': 'Dataset'}, 'url': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T', 'version': '1.0'}, keywords=None, authors=None, title='FLUXCOM-X-BASE evapotranspiration for 2010', temporalCoverageDisplay=None, acknowledgements=None, licence=None)}

In [32]:
coll_evapo = meta.get_collection_meta(coll_2010.parentCollections[0].uri)

coll_evapo.__dict__

{'res': 'https://meta.icos-cp.eu/collections/_l85vWiIV81AifoxCkty50YI',
 'hash': '_l85vWiIV81AifoxCkty50YI',
 'members': [PlainStaticCollection(res='https://meta.icos-cp.eu/collections/6uqHBICxAdAl55NtTkbAYw-s', hash='6uqHBICxAdAl55NtTkbAYw-s', title='FLUXCOM-X-BASE evapotranspiration for 2001'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/MV_IZZgxhXu1EebCL4IP-h7B', hash='MV_IZZgxhXu1EebCL4IP-h7B', title='FLUXCOM-X-BASE evapotranspiration for 2002'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/ewacq5ehLE4Z5WvWIRzk1vFw', hash='ewacq5ehLE4Z5WvWIRzk1vFw', title='FLUXCOM-X-BASE evapotranspiration for 2003'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/BrmOIOtF3iGe7Y-ab0mdBY4x', hash='BrmOIOtF3iGe7Y-ab0mdBY4x', title='FLUXCOM-X-BASE evapotranspiration for 2004'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/M-BBo0WTio_NoQMwUUB8A600', hash='M-BBo0WTio_NoQMwUUB8A600', title='FLUXCOM-X-BASE evapotranspiration for 2005'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/bntRkf8FDGcYqcsTFSPOUJFR', hash='bntRkf8FDGcYqcsTFSPOUJFR', title='FLUXCOM-X-BASE evapotranspiration for 2006'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/5NdWd6yYVVXfKPjgL4xXiv-E', hash='5NdWd6yYVVXfKPjgL4xXiv-E', title='FLUXCOM-X-BASE evapotranspiration for 2007'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/Jzclb4YD5VbeGXCQPcDDX_tj', hash='Jzclb4YD5VbeGXCQPcDDX_tj', title='FLUXCOM-X-BASE evapotranspiration for 2008'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/_R1Spbz5uSdPfrk3bAeM2bOl', hash='_R1Spbz5uSdPfrk3bAeM2bOl', title='FLUXCOM-X-BASE evapotranspiration for 2009'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/_Sno9zc_18Oy3nwaKD-ZYUPO', hash='_Sno9zc_18Oy3nwaKD-ZYUPO', title='FLUXCOM-X-BASE evapotranspiration for 2010'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/gl_Eqx37dvrvX0i_1T2ym2tq', hash='gl_Eqx37dvrvX0i_1T2ym2tq', title='FLUXCOM-X-BASE evapotranspiration for 2011'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/5tziGQpDYKu1rQb3zFd4RNRV', hash='5tziGQpDYKu1rQb3zFd4RNRV', title='FLUXCOM-X-BASE evapotranspiration for 2012'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/kQvCpebkHRlkvopCoAQ1NSvp', hash='kQvCpebkHRlkvopCoAQ1NSvp', title='FLUXCOM-X-BASE evapotranspiration for 2013'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/mLUi20sIat4PxUDNtGDj6xAF', hash='mLUi20sIat4PxUDNtGDj6xAF', title='FLUXCOM-X-BASE evapotranspiration for 2014'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/5PnJ35-MvMxSi2P-YMroFjNX', hash='5PnJ35-MvMxSi2P-YMroFjNX', title='FLUXCOM-X-BASE evapotranspiration for 2015'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/97tEg1r3NoMcarRFz5hT6Gb5', hash='97tEg1r3NoMcarRFz5hT6Gb5', title='FLUXCOM-X-BASE evapotranspiration for 2016'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/fO5mjngamDZjb6NCkhXaJrW5', hash='fO5mjngamDZjb6NCkhXaJrW5', title='FLUXCOM-X-BASE evapotranspiration for 2017'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/JO6oSPoBZDccle0-qeYN8_1e', hash='JO6oSPoBZDccle0-qeYN8_1e', title='FLUXCOM-X-BASE evapotranspiration for 2018'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/M2WjtbHopciqo7p-Q01aK1bK', hash='M2WjtbHopciqo7p-Q01aK1bK', title='FLUXCOM-X-BASE evapotranspiration for 2019'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/0Mhux6I9-K7nI6yo5eQPFBmm', hash='0Mhux6I9-K7nI6yo5eQPFBmm', title='FLUXCOM-X-BASE evapotranspiration for 2020'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/Iabv0HK74sgC5BrBoTWw6EYj', hash='Iabv0HK74sgC5BrBoTWw6EYj', title='FLUXCOM-X-BASE evapotranspiration for 2021')],
 'creator': Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CP', label='CP', comments=[]), name='Carbon Portal', email=None, website=None, webpageDetails=None),
 'title': 'FLUXCOM-X-BASE evapotranspiration for 2001-2021',
 'description': 'This comprehensive collection aggregates FLUXCOM-X-BASE evapotranspiration datasets from 2001 to 2021. Each sub-collection encapsulates global fluxes generated through the FLUXCOM-X framework, employing machine learning models trained on in-situ eddy covariance data. The X-BASE experiment, serving as the foundational configuration, integrates core meteorological data, plant functional type classification, MODIS-based vegetation indices, and land surface temperature as predictors. Utilizing the XGBoost algorithm, these datasets provide meticulous estimations of evapotranspiration, crucial for understanding ecosystem dynamics and climate variability.',
 'previousVersion': None,
 'nextVersion': None,
 'latestVersion': 'https://meta.icos-cp.eu/collections/_l85vWiIV81AifoxCkty50YI',
 'parentCollections': [UriResource(uri='https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T', label='FLUXCOM-X-BASE', comments=[])],
 'doi': '10.18160/5NZG-JMJE',
 'coverage': FeatureCollectionWithGeo(geo={'features': ({'geometry': {'coordinates': ([[-180.0, -90.0], [-180.0, 90.0], [180.0, 90.0], [180.0, -90.0], [-180.0, -90.0]],), 'type': 'Polygon'}, 'properties': {'label': 'Global lat/lon box'}, 'type': 'Feature'},), 'type': 'FeatureCollection'}, features=[LatLonBox(min=Position(lat=-90.0, lon=-180.0, alt=None, label=None, uri=None), max=Position(lat=90.0, lon=180.0, alt=None, label=None, uri=None), label='Global lat/lon box', uri=None)], label=None, uri=None),
 'documentation': None,
 'references': References(citationString='Nelson, J.A., Walther, S., Jung, M., Gans, F., Kraft, B., Weber, U., Hamdi, Z., Duveiller, G., Zhang, W., 2023. FLUXCOM-X-BASE. https://doi.org/10.18160/5NZG-JMJE', citationBibTex='@misc{https://doi.org/10.18160/5nzg-jmje,\n  doi = {10.18160/5NZG-JMJE},\n  url = {https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T},\n  author = {Nelson, Jacob A. and Walther, Sophia and Jung, Martin and Gans, Fabian and Kraft, Basil and Weber, Ulrich and Hamdi, Zayd and Duveiller, Gregory and Zhang, Weijie},\n  keywords = {BIOGEOCHEMICAL CYCLES, CARBON, ECOSYSTEM FUNCTIONS, FLUXCOM, LAND SURFACE, TERRESTRIAL ECOSYSTEMS, VEGETATION, biosphere modeling, carbon flux, FLUXCOM-X},\n  title = {FLUXCOM-X-BASE},\n  publisher = {ICOS ERIC -- Carbon Portal},\n  year = {2023},\n  copyright = {Creative Commons Attribution 4.0 International}\n}', citationRis="TY  - DATA\r\nT1  - FLUXCOM-X-BASE\r\nAU  - Nelson, Jacob A.\r\nAU  - Walther, Sophia\r\nAU  - Jung, Martin\r\nAU  - Gans, Fabian\r\nAU  - Kraft, Basil\r\nAU  - Weber, Ulrich\r\nAU  - Hamdi, Zayd\r\nAU  - Duveiller, Gregory\r\nAU  - Zhang, Weijie\r\nDO  - 10.18160/5NZG-JMJE\r\nUR  - https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T\r\nAB  - The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. \r\nKW  - BIOGEOCHEMICAL CYCLES\r\nKW  - CARBON\r\nKW  - ECOSYSTEM FUNCTIONS\r\nKW  - FLUXCOM\r\nKW  - LAND SURFACE\r\nKW  - TERRESTRIAL ECOSYSTEMS\r\nKW  - VEGETATION\r\nKW  - biosphere modeling\r\nKW  - carbon flux\r\nKW  - FLUXCOM-X\r\nPY  - 2023\r\nPB  - ICOS ERIC -- Carbon Portal\r\nER  -", doi={'contributors': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'creators': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'dates': (), 'descriptions': ({'description': "The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. ", 'descriptionType': 'Abstract'},), 'doi': '10.18160/5NZG-JMJE', 'formats': ('NetCDF (spatial)',), 'fundingReferences': (), 'geoLocations': ({'geoLocationBox': {'eastBoundLongitude': 180.0, 'northBoundLatitude': 90.0, 'southBoundLatitude': -90.0, 'westBoundLongitude': -180.0}, 'geoLocationPlace': 'Global lat/lon box'},), 'publicationYear': 2023, 'publisher': 'ICOS ERIC -- Carbon Portal', 'rightsList': ({'rights': 'Creative Commons Attribution 4.0 International', 'rightsUri': 'https://creativecommons.org/licenses/by/4.0/legalcode'},), 'state': 'findable', 'subjects': ({'subject': 'BIOGEOCHEMICAL CYCLES'}, {'subject': 'CARBON'}, {'subject': 'ECOSYSTEM FUNCTIONS'}, {'subject': 'FLUXCOM'}, {'subject': 'LAND SURFACE'}, {'subject': 'TERRESTRIAL ECOSYSTEMS'}, {'subject': 'VEGETATION'}, {'subject': 'biosphere modeling'}, {'subject': 'carbon flux'}, {'subject': 'FLUXCOM-X'}), 'titles': ({'lang': 'en-us', 'title': 'FLUXCOM-X-BASE'}, {'lang': 'en-us', 'title': 'X-BASE', 'titleType': 'AlternativeTitle'}), 'types': {'resourceType': 'netcdf', 'resourceTypeGeneral': 'Dataset'}, 'url': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T', 'version': '1.0'}, keywords=None, authors=None, title='FLUXCOM-X-BASE evapotranspiration for 2001-2021', temporalCoverageDisplay=None, acknowledgements=None, licence=None)}

In [33]:
evapo_01_21 = meta.get_collection_meta(coll_evapo.parentCollections[0].uri)

evapo_01_21.__dict__

{'res': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T',
 'hash': 'zfwf1Ak2I7OlziGDTX8Xl6_T',
 'members': [PlainStaticCollection(res='https://meta.icos-cp.eu/collections/_l85vWiIV81AifoxCkty50YI', hash='_l85vWiIV81AifoxCkty50YI', title='FLUXCOM-X-BASE evapotranspiration for 2001-2021'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/AYj7-lwcdCLnBXJDoscxQZou', hash='AYj7-lwcdCLnBXJDoscxQZou', title='FLUXCOM-X-BASE gross primary productivity for 2001-2021'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/X_-p994BqVSG6nWJkeK1ALjW', hash='X_-p994BqVSG6nWJkeK1ALjW', title='FLUXCOM-X-BASE net ecosystem exchange for 2001-2021'),
  PlainStaticCollection(res='https://meta.icos-cp.eu/collections/aCBG-AZIJtCCia7bhMYWin1-', hash='aCBG-AZIJtCCia7bhMYWin1-', title='FLUXCOM-X-BASE transpiration for 2001-2021')],
 'creator': Organization(self=UriResource(uri='http://meta.icos-cp.eu/resources/organizations/CP', label='CP', comments=[]), name='Carbon Portal', email=None, website=None, webpageDetails=None),
 'title': 'FLUXCOM-X-BASE',
 'description': None,
 'previousVersion': None,
 'nextVersion': None,
 'latestVersion': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T',
 'parentCollections': [],
 'doi': '10.18160/5NZG-JMJE',
 'coverage': FeatureCollectionWithGeo(geo={'features': ({'geometry': {'coordinates': ([[-180.0, -90.0], [-180.0, 90.0], [180.0, 90.0], [180.0, -90.0], [-180.0, -90.0]],), 'type': 'Polygon'}, 'properties': {'label': 'Global lat/lon box'}, 'type': 'Feature'},), 'type': 'FeatureCollection'}, features=[LatLonBox(min=Position(lat=-90.0, lon=-180.0, alt=None, label=None, uri=None), max=Position(lat=90.0, lon=180.0, alt=None, label=None, uri=None), label='Global lat/lon box', uri=None)], label=None, uri=None),
 'documentation': None,
 'references': References(citationString='Nelson, J.A., Walther, S., Jung, M., Gans, F., Kraft, B., Weber, U., Hamdi, Z., Duveiller, G., Zhang, W., 2023. FLUXCOM-X-BASE. https://doi.org/10.18160/5NZG-JMJE', citationBibTex='@misc{https://doi.org/10.18160/5nzg-jmje,\n  doi = {10.18160/5NZG-JMJE},\n  url = {https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T},\n  author = {Nelson, Jacob A. and Walther, Sophia and Jung, Martin and Gans, Fabian and Kraft, Basil and Weber, Ulrich and Hamdi, Zayd and Duveiller, Gregory and Zhang, Weijie},\n  keywords = {BIOGEOCHEMICAL CYCLES, CARBON, ECOSYSTEM FUNCTIONS, FLUXCOM, LAND SURFACE, TERRESTRIAL ECOSYSTEMS, VEGETATION, biosphere modeling, carbon flux, FLUXCOM-X},\n  title = {FLUXCOM-X-BASE},\n  publisher = {ICOS ERIC -- Carbon Portal},\n  year = {2023},\n  copyright = {Creative Commons Attribution 4.0 International}\n}', citationRis="TY  - DATA\r\nT1  - FLUXCOM-X-BASE\r\nAU  - Nelson, Jacob A.\r\nAU  - Walther, Sophia\r\nAU  - Jung, Martin\r\nAU  - Gans, Fabian\r\nAU  - Kraft, Basil\r\nAU  - Weber, Ulrich\r\nAU  - Hamdi, Zayd\r\nAU  - Duveiller, Gregory\r\nAU  - Zhang, Weijie\r\nDO  - 10.18160/5NZG-JMJE\r\nUR  - https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T\r\nAB  - The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. \r\nKW  - BIOGEOCHEMICAL CYCLES\r\nKW  - CARBON\r\nKW  - ECOSYSTEM FUNCTIONS\r\nKW  - FLUXCOM\r\nKW  - LAND SURFACE\r\nKW  - TERRESTRIAL ECOSYSTEMS\r\nKW  - VEGETATION\r\nKW  - biosphere modeling\r\nKW  - carbon flux\r\nKW  - FLUXCOM-X\r\nPY  - 2023\r\nPB  - ICOS ERIC -- Carbon Portal\r\nER  -", doi={'contributors': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'contributorType': 'Producer', 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'creators': ({'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Nelson', 'givenName': 'Jacob A.', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-4663-2420', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Walther', 'givenName': 'Sophia', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1681-9304', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Jung', 'givenName': 'Martin', 'nameIdentifiers': (), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Gans', 'givenName': 'Fabian', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-9614-0435', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Kraft', 'givenName': 'Basil', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-8491-2730', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Weber', 'givenName': 'Ulrich', 'nameIdentifiers': ({'nameIdentifier': '0000-0001-7116-035X', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Hamdi', 'givenName': 'Zayd', 'nameIdentifiers': ({'nameIdentifier': '0000-0003-1658-8243', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Duveiller', 'givenName': 'Gregory', 'nameIdentifiers': ({'nameIdentifier': '0000-0002-6471-8404', 'nameIdentifierScheme': 'ORCID', 'schemeUri': 'http://orcid.org/'},), 'nameType': 'Personal'}, {'affiliation': ({'name': 'Department Biogeochemical Integration, Max-Planck-Institute for Biogeochemistry, Germany'},), 'familyName': 'Zhang', 'givenName': 'Weijie', 'nameIdentifiers': (), 'nameType': 'Personal'}), 'dates': (), 'descriptions': ({'description': "The X-BASE products are global fluxes based on the FLUXCOM-X framework which trains machine learning models on in-situ eddy covariance data and uses them to produce these global products. The X-BASE experiment is a basic configuration to serve as a baseline for the FLUXCOM-X framework and includes as predictors the core meteorological data, plant functional type classification as well as MODIS based vegetation indices and land surface temperature. XGBoost was used as the machine learning algorithm.\n\nPublished paper: \nNelson, J. A., Walther, S., Gans, F., Kraft, B., Weber, U., Novick, K., Buchmann, N., Migliavacca, M., Wohlfahrt, G., Šigut, L., Ibrom, A., Papale, D., Göckede, M., Duveiller, G., Knohl, A., Hörtnagl, L., Scott, R. L., Zhang, W., Hamdi, Z. M., Reichstein, M., Aranda-Barranco, S., Ardö, J., Op de Beeck, M., Billesbach, D., Bowling, D., Bracho, R., Brümmer, C., Camps-Valls, G., Chen, S., Cleverly, J. R., Desai, A., Dong, G., El-Madany, T. S., Euskirchen, E. S., Feigenwinter, I., Galvagno, M., Gerosa, G. A., Gielen, B., Goded, I., Goslee, S., Gough, C. M., Heinesch, B., Ichii, K., Jackowicz-Korczynski, M. A., Klosterhalfen, A., Knox, S., Kobayashi, H., Kohonen, K.-M., Korkiakoski, M., Mammarella, I., Gharun, M., Marzuoli, R., Matamala, R., Metzger, S., Montagnani, L., Nicolini, G., O'Halloran, T., Ourcival, J.-M., Peichl, M., Pendall, E., Ruiz Reverter, B., Roland, M., Sabbatini, S., Sachs, T., Schmidt, M., Schwalm, C. R., Shekhar, A., Silberstein, R., Silveira, M. L., Spano, D., Tagesson, T., Tramontana, G., Trotta, C., Turco, F., Vesala, T., Vincke, C., Vitale, D., Vivoni, E. R., Wang, Y., Woodgate, W., Yepez, E. A., Zhang, J., Zona, D., and Jung, M.: X-BASE: the first terrestrial carbon and water flux products from an extended data-driven scaling framework, FLUXCOM-X, Biogeosciences, 21, 5079–5115, https://doi.org/10.5194/bg-21-5079-2024, 2024. ", 'descriptionType': 'Abstract'},), 'doi': '10.18160/5NZG-JMJE', 'formats': ('NetCDF (spatial)',), 'fundingReferences': (), 'geoLocations': ({'geoLocationBox': {'eastBoundLongitude': 180.0, 'northBoundLatitude': 90.0, 'southBoundLatitude': -90.0, 'westBoundLongitude': -180.0}, 'geoLocationPlace': 'Global lat/lon box'},), 'publicationYear': 2023, 'publisher': 'ICOS ERIC -- Carbon Portal', 'rightsList': ({'rights': 'Creative Commons Attribution 4.0 International', 'rightsUri': 'https://creativecommons.org/licenses/by/4.0/legalcode'},), 'state': 'findable', 'subjects': ({'subject': 'BIOGEOCHEMICAL CYCLES'}, {'subject': 'CARBON'}, {'subject': 'ECOSYSTEM FUNCTIONS'}, {'subject': 'FLUXCOM'}, {'subject': 'LAND SURFACE'}, {'subject': 'TERRESTRIAL ECOSYSTEMS'}, {'subject': 'VEGETATION'}, {'subject': 'biosphere modeling'}, {'subject': 'carbon flux'}, {'subject': 'FLUXCOM-X'}), 'titles': ({'lang': 'en-us', 'title': 'FLUXCOM-X-BASE'}, {'lang': 'en-us', 'title': 'X-BASE', 'titleType': 'AlternativeTitle'}), 'types': {'resourceType': 'netcdf', 'resourceTypeGeneral': 'Dataset'}, 'url': 'https://meta.icos-cp.eu/collections/zfwf1Ak2I7OlziGDTX8Xl6_T', 'version': '1.0'}, keywords=None, authors=None, title='FLUXCOM-X-BASE', temporalCoverageDisplay=None, acknowledgements=None, licence=None)}